#!/usr/bin/env node
// Writes the gitignored host/integrations/secrets.local.cjs from build-time
// environment variables. Never commit the generated file -- it's excluded
// in .gitignore. See providers.cjs for why Google's Desktop-app client
// needs a client_secret at all, and why it can't live in a tracked file
// (GitHub's push protection rejects it regardless of Google's own "not
// meant to stay confidential for Desktop clients" stance).
const fs = require("node:fs");
const path = require("node:path");

const outFile = path.join(
  __dirname,
  "../host/integrations/secrets.local.cjs",
);
const googleClientSecret = process.env.YANA_GOOGLE_CLIENT_SECRET || null;

if (!googleClientSecret) {
  console.log(
    "[write-secrets] YANA_GOOGLE_CLIENT_SECRET not set -- Google sign-in will fall back to PKCE-only, which this Desktop-app Client ID rejects. Skipping file write.",
  );
  process.exit(0);
}

fs.writeFileSync(
  outFile,
  `// Generated by scripts/write-secrets.cjs -- do not edit or commit.\nmodule.exports = { googleClientSecret: ${JSON.stringify(googleClientSecret)} };\n`,
  { mode: 0o600 },
);
console.log(`[write-secrets] wrote ${outFile}`);
