const vi = Object.freeze({
    'plugins.catalog.promptTemplates.title': 'Mẫu prompt',
    'plugins.catalog.promptTemplates.description': 'Công cụ prompt theo mẫu, hỗ trợ biến, sao chép và xuất.',
    'plugins.status.standard': 'tiêu chuẩn',
    'plugins.builtin.commentPolish.name': 'Chỉnh chú thích mã',
    'plugins.builtin.commentPolish.desc': 'Chỉnh nhẹ các chú thích mã sau {{code}}',
    'plugins.builtin.commentPolish.line1': 'Chỉnh nhẹ các chú thích mã sau',
    'plugins.builtin.ruleAck.name': 'Xác nhận quy tắc',
    'plugins.builtin.ruleAck.desc': 'Tạo phản hồi xác nhận quy tắc',
    'plugins.builtin.ruleAck.line1': 'Hãy làm theo【{{rule}}】, nhận được thì phản hồi',
    // Global
    'lang.zh': 'Tiếng Trung',
    'lang.en': 'Tiếng Anh',
    'lang.vi': 'Tiếng Việt',
    'lang.label': 'Ngôn ngữ',
    'nav.topTabs.aria': 'Điều hướng',

    // Common
    'common.all': 'Tất cả',
    'common.copy': 'Sao chép',
    'common.paste': 'Dán',
    'common.edit': 'Chỉnh sửa',
    'common.install': 'Cài đặt',
    'common.update': 'Cập nhật',
    'common.uninstall': 'Gỡ cài đặt',
    'common.official': 'Chính thức',
    'common.custom': 'Tùy chỉnh',
    'common.rules': 'Quy tắc',
    'common.troubleshooting': 'Khắc phục sự cố',
    'common.command': 'Lệnh',
    'common.mirror': 'Nguồn',
    'common.packageManager': 'Trình quản lý gói',
    'common.action': 'Thao tác',
    'common.targets': 'Mục tiêu',
    'common.currentPm': 'Trình quản lý gói',
    'common.currentAction': 'Thao tác hiện tại',
    'common.mirrorActive': 'Nguồn',
    'common.defaultOfficial': 'Mặc định',
    'common.cancel': 'Hủy',
    'common.confirm': 'Xác nhận',
    'common.add': 'Thêm',
    'common.save': 'Lưu',
    'common.saveApply': 'Lưu & áp dụng',
    'common.close': 'Đóng',
    'common.delete': 'Xóa',
    'common.clear': 'Xóa',
    'common.show': 'Hiện',
    'common.hide': 'Ẩn',
    'common.detail': 'Chi tiết',
    'common.refresh': 'Làm mới',
    'common.refreshing': 'Đang làm mới...',
    'common.loading': 'Đang tải...',
    'common.saving': 'Đang lưu...',
    'common.sending': 'Đang gửi...',
    'common.scanning': 'Đang quét...',
    'common.export': 'Xuất',
    'common.import': 'Nhập',
    'common.apply': 'Áp dụng',
    'common.applying': 'Đang áp dụng...',
    'common.confirming': 'Đang xác nhận...',
    'common.writeToEditor': 'Ghi vào trình soạn thảo',
    'common.refreshFromText': 'Làm mới từ văn bản',
    'common.backToEdit': 'Quay lại chỉnh sửa',
    'common.selectAll': 'Chọn tất cả',
    'common.unselectAll': 'Bỏ chọn tất cả',
    'common.resetFilters': 'Đặt lại bộ lọc',
    'common.notEditable': 'Không thể chỉnh sửa',
    'common.notDeletable': 'Không thể xóa',
    'common.notLoaded': 'Chưa tải',
    'common.exists': 'Đã tồn tại',
    'common.notExistsWillCreateOnApply': 'Không tồn tại. Sẽ được tạo khi áp dụng.',
    'common.notExistsWillCreateOnSave': 'Không tồn tại. Sẽ được tạo khi lưu.',
    'common.none': 'Không có',
    'common.configured': 'Đã cấu hình',
    'common.notConfigured': 'Chưa cấu hình',
    'common.notSelected': 'Chưa chọn',

    // Roles / labels
    'role.you': 'Bạn',
    'role.provider': 'Nhà cung cấp',
    'label.model': 'Mẫu:',

    // Top tabs
    'tab.dashboard': 'Tổng quan',
    'tab.docs': 'Tài liệu',
    'tab.config': 'Cấu hình',
    'tab.sessions': 'Phiên',
    'tab.usage': 'Sử dụng',
    'tab.orchestration': 'Tác vụ',
    'tab.market': 'Skills',
    'tab.plugins': 'Plugin',
    'tab.settings': 'Cài đặt',

    // Side rail section titles
    'side.overview': 'Tổng quan',
    'side.docs': 'Tài liệu',
    'side.config': 'Cấu hình',
    'side.sessions': 'Phiên',
    'side.plugins': 'Plugin',
    'side.system': 'Hệ thống',
    'side.orchestration': 'Tác vụ',
    'side.skills': 'Skills',

    // Side rail items
    'side.overview.doctor': 'Doctor',
    'side.overview.doctor.meta': 'Tổng quan / Chẩn đoán',
    'side.docs.cliInstall': 'Cài CLI',
    'side.docs.cliInstall.meta': 'Cài đặt / Cập nhật / Gỡ',
    'side.update.available': 'Có bản cập nhật',
    'side.update.availableWithVersion': 'Có bản cập nhật v{version}',
    'side.update.meta': 'Mở lệnh cập nhật',
    'side.update.metaVersions': 'Hiện tại v{current} → mới nhất v{latest}',
    'side.update.checkFailed': 'Không thể kiểm tra phiên bản mới nhất',
    'side.update.check': 'Kiểm tra cập nhật',
    'side.update.checking': 'Đang kiểm tra cập nhật…',
    'side.update.checkingMeta': 'Đang kết nối npm registry',
    'side.update.upToDate': 'Đã là phiên bản mới nhất',
    'side.update.currentOnly': 'Hiện tại v{current}',
    'side.update.retry': 'Thử kiểm tra phiên bản lại',
    'side.config.codex': 'Codex',
    'side.config.codex.meta': 'Provider / Model',
    'side.config.claude': 'Claude Code',
    'side.config.claude.meta': 'Cài đặt Claude',
    'side.config.openclaw': 'OpenClaw',
    'side.config.openclaw.meta': 'JSON5 / AGENTS',
    'side.sessions.browser': 'Trình duyệt phiên',
    'side.sessions.browser.meta': 'Duyệt / Xuất / Dọn dẹp',
    'side.plugins.tools': 'Công cụ prompt',
    'side.plugins.tools.meta': 'Mẫu / Biến',
    'side.system.settings': 'Cài đặt runtime',
    'side.system.settings.meta': 'Dữ liệu / Sao lưu',
    'side.newTab': 'Tab mới',
    'config.localBridge.enabledCount': 'Đã bật {enabled}/{total}',
    'toolConfig.allow': 'Cho phép ghi',
    'toolConfig.viewOnly': 'Chỉ đọc',
    'toolConfig.enableWrite': 'Bật ghi',
    'toolConfig.allowToast': 'Đã bật ghi',
    'toolConfig.viewOnlyToast': 'Đã chuyển về chỉ đọc',
    'toolConfig.saveFailed': 'Không lưu được công tắc ghi',
    'toolConfig.confirmTitle': 'Bật quyền ghi',
    'toolConfig.confirmAllow': 'Bật ghi',
    'toolConfig.codex.title': 'Ghi provider Codex',
    'toolConfig.codex.desc': 'Provider Codex mặc định chỉ đọc; bật công tắc này trước khi ghi cấu hình ~/.codex.',
    'toolConfig.codex.lockedTitle': 'Provider Codex đang chỉ đọc',
    'toolConfig.codex.lockedDesc': 'Cấu hình tài khoản Codex sẽ không bị sửa. Hãy bật ghi trong tab này để thêm, chuyển, sửa hoặc xóa provider.',
    'toolConfig.codex.confirmMessage': 'Sau khi bật, thao tác provider trong tab Codex có thể ghi ~/.codex/config.toml, auth hoặc cấu hình model.',
    'toolConfig.claude.title': 'Ghi provider Claude',
    'toolConfig.claude.desc': 'Provider Claude mặc định chỉ đọc; bật công tắc này trước khi ghi Claude settings.',
    'toolConfig.claude.lockedTitle': 'Provider Claude đang chỉ đọc',
    'toolConfig.claude.lockedDesc': 'Cấu hình Claude sẽ không bị sửa. Hãy bật ghi trong tab này để thêm, áp dụng, sửa hoặc xóa provider.',
    'toolConfig.claude.confirmMessage': 'Sau khi bật, thao tác áp dụng trong tab Claude có thể ghi ~/.claude/settings.json và cấu hình Claude liên quan.',
    'side.usage.meta': 'Thống kê / Xu hướng',
    'side.orchestration.meta': 'Kế hoạch / Hàng đợi / Runs',

    // Header titles
    'kicker.dashboard': 'Doctor',
    'kicker.config': 'Cấu hình',
    'kicker.sessions': 'Phiên',
    'kicker.usage': 'Sử dụng',
    'kicker.orchestration': 'Tác vụ',
    'kicker.market': 'Skills',
    'kicker.plugins': 'Plugin',
    'kicker.docs': 'Tài liệu',
    'kicker.settings': 'Cài đặt',
    'kicker.trash': 'Thùng rác',

    'title.dashboard': 'Dashboard / Doctor',
    'title.config': 'Bảng điều khiển cấu hình cục bộ',
    'title.sessions': 'Phiên & Xuất',
    'title.usage': 'Thống kê & Xu hướng',
    'title.orchestration': 'Điều phối tác vụ',
    'title.market': 'Cài đặt & Đồng bộ Skills',
    'title.plugins': 'Plugin & Mẫu',
    'title.docs': 'Cài CLI & Tài liệu',
    'title.settings': 'Hệ thống & Dữ liệu',

    'subtitle.dashboard': 'Tổng hợp trạng thái và chẩn đoán.',
    'subtitle.config': 'Quản lý cấu hình và mô hình cục bộ.',
    'subtitle.sessions': 'Duyệt và xuất các phiên.',
    'subtitle.usage': 'Xem sử dụng trong 7/30 ngày gần đây.',
    'subtitle.orchestration': 'Lập kế hoạch, xếp hàng, chạy và xem lại tác vụ cục bộ.',
    'subtitle.market': 'Quản lý skills cục bộ.',
    'subtitle.plugins': 'Quản lý plugin và mẫu tái sử dụng.',
    'subtitle.docs': 'Lệnh cài CLI và hướng dẫn.',
    'subtitle.settings': 'Quản lý tải xuống, thư mục và dữ liệu.',


    // Task orchestration readiness
    // Trash
    'settings.trash.empty': 'Thùng rác trống',
    'settings.trash.emptyHint': 'Không có phiên đã xóa trong thời gian lưu {days} ngày.',
    'settings.trash.retentionUnit': 'ngày',

    'orchestration.readiness.target.label': 'Mục tiêu',
    'orchestration.readiness.target.done': 'Đã viết mục tiêu',
    'orchestration.readiness.target.missing': 'Chưa viết mục tiêu',
    'orchestration.readiness.engine.label': 'Chiến lược chạy',
    'orchestration.readiness.engine.codex': 'Dùng Codex để lập kế hoạch node',
    'orchestration.readiness.workflow.done': 'Đã chọn {count} Workflow',
    'orchestration.readiness.workflow.missing': 'Chưa chọn Workflow ID',
    'orchestration.readiness.scope.label': 'Phạm vi',
    'orchestration.readiness.scope.done': 'Đã bổ sung ghi chú',
    'orchestration.readiness.scope.writeHint': 'Nên bổ sung ghi chú trước khi ghi',
    'orchestration.readiness.scope.readonlyHint': 'Đang ở chế độ chỉ đọc, có thể thử ngay',
    'orchestration.readiness.preview.label': 'Xem trước',
    'orchestration.readiness.preview.missing': 'Chưa tạo kế hoạch',
    'orchestration.readiness.preview.blocked': 'Có {count} mục chặn',
    'orchestration.readiness.preview.ready': 'Kế hoạch sẵn sàng, {count} node',
    'orchestration.readiness.empty.title': 'Viết mục tiêu trước',
    'orchestration.readiness.empty.summary': 'Mô tả rõ kết quả cần đạt, rồi để bộ điều phối tách thành các node.',
    'orchestration.readiness.workflow.title': 'Thiếu Workflow',
    'orchestration.readiness.workflow.summary': 'Bạn đã chọn chế độ Workflow nhưng chưa chỉ định quy trình tái sử dụng.',
    'orchestration.readiness.preview.title': 'Nên xem trước trước',
    'orchestration.readiness.preview.summary': 'Bản nháp đã đủ hình hài; hãy tạo kế hoạch để kiểm tra node và phụ thuộc.',
    'orchestration.readiness.blocked.title': 'Bản xem trước có mục chặn',
    'orchestration.readiness.blocked.summary': 'Kế hoạch hiện còn {count} mục chặn, hãy xử lý chúng trước.',
    'orchestration.readiness.warn.title': 'Có thể chạy nhưng có cảnh báo',
    'orchestration.readiness.warn.summary': 'Kế hoạch đã được tạo, nhưng còn {count} cảnh báo nên xem trước.',
    'orchestration.readiness.dryRun.title': 'Phù hợp để chạy thử',
    'orchestration.readiness.dryRun.summary': 'Bây giờ có thể chạy thử an toàn rồi xem kết quả trước khi chạy thật.',
    'orchestration.readiness.ready.title': 'Sẵn sàng chạy',
    'orchestration.readiness.ready.withFollowUps': 'Mục tiêu chính và hành động tiếp theo đã sẵn sàng; có thể chạy ngay hoặc đưa vào hàng đợi.',
    'orchestration.readiness.ready.summary': 'Mục tiêu chính đã đủ rõ; có thể chạy ngay hoặc đưa vào hàng đợi.',

    // Settings panel
    'settings.language.sideLabel': 'Ngôn ngữ: {language}',
    'settings.language.title': 'Ngôn ngữ',
    'settings.language.meta': 'Chọn ngôn ngữ hiển thị cho Web UI',
    'settings.language.label': 'Ngôn ngữ giao diện',
    'settings.language.hint': 'Tùy chọn ngôn ngữ được lưu trong trình duyệt này.',

    'settings.webhook.title': 'Webhook',
    'settings.webhook.meta': 'Gửi thông báo sự kiện tới dịch vụ bên ngoài',
    'settings.webhook.enabled': 'Đã bật',
    'settings.webhook.disabled': 'Chưa bật',
    'settings.webhook.enable': 'Bật',
    'settings.webhook.edit': 'Sửa',
    'settings.webhook.configure': 'Cấu hình',
    'settings.webhook.modalTitle': 'Cài đặt Webhook',
    'settings.webhook.enabledLabel': 'Trạng thái',
    'settings.webhook.enableToggle': 'Bật webhook',
    'settings.webhook.urlLabel': 'Webhook URL',
    'settings.webhook.eventsLabel': 'Sự kiện',

    // Dashboard / doctor
    'dashboard.doctor.title': 'Doctor',
    'dashboard.doctor.runChecks': 'Chạy kiểm tra',
    'dashboard.doctor.checking': 'Đang kiểm tra...',
    'dashboard.doctor.export': 'Xuất báo cáo',

    // Claude target API
    'claude.targetApi.label': 'API đích',
    'claude.targetApi.responses': 'Anthropic',
    'claude.targetApi.chatCompletions': 'OpenAI Chat Completions (/v1/chat/completions)',
    'claude.targetApi.ollama': 'Ollama Chat (/api/chat)',
    'claude.targetApi.chatCompletionsBadge': 'OpenAI Chat Completions',
    'claude.targetApi.ollamaBadge': 'Ollama',
    'claude.targetApi.hint': 'Khi chọn Chat Completions hoặc Ollama, proxy tương thích Claude sẽ chuyển đổi nội bộ mà không thay đổi wire_api của Codex provider; Ollama không cần API key.',

    // Toasts
    'toast.copy.empty': 'Không có gì để sao chép',
    'toast.copy.ok': 'Đã sao chép',
    'toast.copy.fail': 'Sao chép thất bại',
    'toast.save.ok': 'Đã lưu',
    'toast.save.fail': 'Lưu thất bại',
    'toast.delete.ok': 'Đã xóa',
    'toast.delete.fail': 'Xóa thất bại',
    'toast.operation.success': 'Thao tác thành công',
    'toast.load.fail': 'Tải tệp thất bại',
    'toast.apply.success': 'Đã áp dụng cấu hình',
    'toast.apply.fail': 'Áp dụng cấu hình thất bại',
    'toast.check.success': 'Kiểm tra thành công',
    'toast.check.fail': 'Kiểm tra thất bại',
    'toast.noChanges': 'Không phát hiện thay đổi',
    'toast.template.loadFail': 'Tải mẫu thất bại',
    'toast.template.empty': 'Mẫu không được để trống',
    'toast.template.applied': 'Đã áp dụng mẫu',
    'toast.template.appliedButRefreshFail': 'Đã áp dụng mẫu, nhưng làm mới giao diện thất bại. Vui lòng làm mới thủ công',
    'toast.template.applyFail': 'Áp dụng mẫu thất bại',
    'toast.provider.addFail': 'Thêm thất bại',
    'toast.provider.notDeletable': 'Provider này là mục dành riêng, không thể xóa',
    'toast.provider.deletedAndSwitched': 'Đã xóa provider, tự động chuyển sang {provider}{model}',
    'toast.provider.notEditable': 'Provider này là mục dành riêng, không thể chỉnh sửa',
    'toast.provider.updateFail': 'Cập nhật thất bại',
    'toast.provider.resetSuccess': 'Đã cài đặt lại cấu hình{backup}',
    'toast.provider.resetFail': 'Cài đặt lại thất bại',
    'toast.provider.fieldsRequired': 'Tên, URL, API Key và tên mô hình là bắt buộc',
    'toast.provider.urlRequired': 'URL là bắt buộc',
    'toast.claude.modelRequired': 'Vui lòng nhập mô hình',
    'toast.claude.apiKeyRequired': 'Vui lòng cấu hình API Key trước',
    'toast.claude.checkConfig': 'Vui lòng kiểm tra cấu hình Claude',
    'toast.claude.savedWithoutKey': 'Đã lưu (chưa điền API Key)',
    'toast.claude.applied': 'Cấu hình Claude đã được áp dụng',
    'toast.claude.exists': 'Cấu hình đã tồn tại',
    'toast.claude.keepOne': 'Giữ ít nhất một mục',
    'toast.claude.externalAuth': 'Sử dụng xác thực bên ngoài, không cần API Key',
    'toast.claude.balanceEnabled': 'Đã bật cân bằng tải cục bộ Claude',
    'toast.claude.balanceDisabled': 'Đã tắt cân bằng tải cục bộ Claude',
    'toast.claude.balanceEnableFail': 'Không thể bật cân bằng tải',
    'toast.claude.balanceRequireProvider': 'Vui lòng thêm và cấu hình ít nhất một nhà cung cấp Claude',
    'toast.claude.loadSettingsFail': 'Tải cài đặt Claude thất bại',
    'validation.claude.nameRequired': 'Tên cấu hình là bắt buộc',
    'validation.claude.nameExists': 'Tên đã tồn tại',
    'validation.claude.apiKeyRequired': 'API Key là bắt buộc',
    'validation.claude.baseUrlRequired': 'Base URL là bắt buộc',
    'validation.claude.baseUrlHttpOnly': 'Base URL chỉ hỗ trợ http/https',
    'validation.claude.modelRequired': 'Tên mô hình là bắt buộc',
    'modal.claudeDelete.title': 'Xóa cấu hình Claude',
    'modal.claudeDelete.message': 'Xóa cấu hình "{name}"?',
    'modal.claudeDelete.confirm': 'Xóa',
    'modal.claudeDelete.cancel': 'Hủy',

    // CLI
    'cli.missing.title': '{name} CLI chưa được cài đặt',
    'cli.missing.subtitle': 'Vui lòng cài đặt {name} CLI trước khi tiếp tục sử dụng trang này.',
    'cli.missing.openDocs': 'Mở hướng dẫn cài đặt',
    'cli.missing.commandAria': 'Lệnh cài đặt {name} CLI',

    // Brand
    'brand.kicker.workspace': 'Không gian làm việc',
    'brand.subtitle.localConfigSessionsWorkspace': 'Cấu hình cục bộ & không gian làm việc phiên',

    // Confirm
    'confirm.aria': 'Xác nhận thao tác',
    'confirm.title.default': 'Vui lòng xác nhận thao tác',
    'confirm.ok': 'Xác nhận',
    'confirm.cancel': 'Hủy',

    // Fields
    'field.name': 'Tên',
    'field.configName': 'Tên cấu hình',
    'field.apiEndpoint': 'Endpoint API',
    'field.apiKey': 'Khóa xác thực',
    'field.baseUrl': 'Base URL',
    'field.provider': 'Nhà cung cấp',
    'field.providerName': 'Tên nhà cung cấp',
    'field.modelName': 'Tên mô hình',
    'field.model': 'Mô hình',
    'field.message': 'Tin nhắn',
    'field.varName': 'Tên biến',
    'field.targetFile': 'Tệp đích',
    'field.modelId': 'ID mô hình',
    'field.displayName': 'Tên hiển thị',
    'field.contextAndMaxOutput': 'Ngữ cảnh & đầu ra tối đa',
    'field.apiType': 'Loại API',
    'field.env': 'Biến môi trường',
    'field.allow': 'Cho phép',
    'field.deny': 'Từ chối',
    'field.contextWindow': 'Độ dài ngữ cảnh',
    'field.maxOutput': 'Đầu ra tối đa',
    'field.useBuiltinTransform': 'Dùng chuyển đổi tích hợp (tương thích định dạng OpenAI)',

    // Placeholders
    'placeholder.providerNameExample': 'Ví dụ: myapi',
    'placeholder.apiEndpointExample': 'https://api.example.com/v1',
    'placeholder.providerName': 'Tên nhà cung cấp',
    'placeholder.keepUnchanged': 'Để trống để giữ nguyên',
    'placeholder.modelExample': 'Ví dụ: gpt-5',
    'placeholder.configNameExample': 'Ví dụ: ZhipuAI GLM',
    'placeholder.apiKeyExampleClaude': 'sk-ant-...',
    'placeholder.baseUrlExampleClaude': 'https://open.bigmodel.cn/api/anthropic',
    'placeholder.selectProvider': 'Vui lòng chọn nhà cung cấp',
    'placeholder.openclawConfigNameExample': 'Ví dụ: Cấu hình mặc định',
    'placeholder.apiTypeExample': 'Ví dụ: openai-responses',
    'placeholder.modelIdExample': 'Ví dụ: gpt-4.1',
    'placeholder.modelNameOptional': 'Để trống sẽ dùng ID mô hình',

    // Hints
    'hint.keepKeyUnchanged': 'Để trống nghĩa là không thay đổi khóa',
    'hint.useBuiltinTransform': 'Khi bật: base_url sẽ trỏ đến dịch vụ chuyển đổi tích hợp của codexmate; token Codex sẽ cố định là codexmate.',
    'hint.emptyNoChange': 'Để trống nghĩa là không thay đổi cấu hình hiện tại.',

    // Tabs
    'tab.config.codex': 'Codex',
    'tab.config.claude': 'Claude',
    'tab.config.openclaw': 'OpenClaw',

    // Sidebar
    'side.plugins.templatesCount': '{count} mẫu',

    // Dashboard doctor export
    'dashboard.doctor.export.json': 'Xuất JSON',
    'dashboard.doctor.export.md': 'Xuất Markdown',
    'dashboard.doctor.open': 'Mở',

    // Doctor actions
    'doctor.action.openConfig': 'Mở Cấu hình',
    'doctor.action.checkProvider': 'Kiểm tra cấu hình Provider',
    'doctor.action.openUsage': 'Mở Usage',
    'doctor.action.openSessions': 'Mở Sessions',
    'doctor.action.openTasks': 'Mở Tasks',
    'doctor.action.viewTaskLogs': 'Xem Tasks / Logs',
    'doctor.action.openSkills': 'Mở Skills',

    // Doctor issues
    'doctor.issue.configNotReady.problem': 'Tệp cấu hình chưa sẵn sàng',
    'doctor.issue.configNotReady.impact': 'Có thể khiến provider/model không đọc được, danh sách mô hình và yêu cầu sẽ không khả dụng.',
    'doctor.issue.providerUnreachable.problem.remote-model-probe-unreachable': 'Provider không thể truy cập',
    'doctor.issue.providerUnreachable.problem.remote-model-probe-auth-failed': 'Xác thực Provider thất bại',
    'doctor.issue.providerUnreachable.problem.remote-model-probe-not-found': 'Provider trả về 404',
    'doctor.issue.providerUnreachable.problem.remote-model-probe-http-error': 'Provider trả về lỗi HTTP',
    'doctor.issue.providerUnreachable.problem.remote-model-probe-error': 'Kiểm tra Provider thất bại',
    'doctor.issue.providerUnreachable.problem.unknown': 'Provider không khả dụng',
    'doctor.issue.providerUnreachable.impactAuth': 'Xác thực thất bại sẽ khiến danh sách mô hình/yêu cầu trả về 401/403.',
    'doctor.issue.providerUnreachable.impactNetwork': 'Không thể kết nối sẽ khiến danh sách mô hình/yêu cầu thất bại hoặc hết thời gian.',
    'doctor.issue.configHealthFailed.problem': 'Kiểm tra sức khỏe cấu hình thất bại',
    'doctor.issue.configHealthFailed.impact': 'Có thể khiến một số tính năng không khả dụng hoặc hoạt động không đúng.',
    'doctor.issue.usageError.problem': 'Lỗi thống kê Usage',
    'doctor.issue.usageError.impact': 'Trang Usage có thể không hiển thị xu hướng/tóm tắt, và chẩn đoán sử dụng của Doctor cũng sẽ bị thiếu.',
    'doctor.issue.usageMissingModel.problem': 'Một số phiên thiếu thông tin mô hình',
    'doctor.issue.usageMissingModel.impact': 'Sẽ làm cho việc quy kết sử dụng và ước tính chi phí không chính xác.',
    'doctor.issue.tasksError.problem': 'Đọc trạng thái Tasks thất bại',
    'doctor.issue.tasksError.impact': 'Có thể khiến hàng đợi điều phối/lịch sử chạy không hiển thị được.',
    'doctor.issue.tasksFailed.problem': 'Có tác vụ chạy thất bại',
    'doctor.issue.tasksFailed.impact': 'Có thể làm gián đoạn quy trình tự động, cần xem log và thử lại hoặc sửa đầu vào.',
    'doctor.issue.skillsError.problem': 'Đọc danh sách Skills thất bại',
    'doctor.issue.skillsError.impact': 'Sẽ khiến trang Skills không hiển thị hoặc cài đặt bình thường.',
    'doctor.issue.skillsRootMissing.problem': 'Thư mục Skills không tồn tại',
    'doctor.issue.skillsRootMissing.impact': 'Sẽ khiến cài đặt/quét Skills trống; hãy khởi tạo thư mục theo hướng dẫn trong Settings/Docs.',
    'doctor.issue.skillsMissingFiles.problem': 'Có skill thiếu skill.json',
    'doctor.issue.skillsMissingFiles.impact': 'Sẽ khiến một số skill không thể chạy hoặc đồng bộ.',

    // Dashboard cards
    'dashboard.card.config': 'Cấu hình',
    'dashboard.card.sessions': 'Phiên',
    'dashboard.card.usage': 'Sử dụng',
    'dashboard.card.tasks': 'Tác vụ',
    'dashboard.card.skills': 'Skills',
    'dashboard.kv.model': 'Mô hình',
    'dashboard.kv.issue': 'Vấn đề',
    'dashboard.kv.active': 'Hiện tại',
    'dashboard.kv.sessions': 'Số phiên',
    'dashboard.kv.missingModel': 'Thiếu mô hình',
    'dashboard.kv.blockers': 'Chặn',
    'dashboard.kv.runs': 'Lần chạy',
    'dashboard.kv.target': 'Mục tiêu',
    'dashboard.kv.root': 'Thư mục',
    'dashboard.status.health': 'Sức khỏe',
    'dashboard.status.busy': 'Trạng thái',
    'dashboard.status.models': 'Mô hình',
    'dashboard.busy.init': 'Khởi tạo',
    'dashboard.busy.sessions': 'Tải phiên',
    'dashboard.busy.models': 'Tải mô hình',
    'dashboard.busy.configApply': 'Áp dụng cấu hình',
    'dashboard.busy.agents': 'Lưu AGENTS',
    'dashboard.busy.skills': 'Quản lý Skills',
    'dashboard.busy.tasks': 'Điều phối tác vụ',
    'dashboard.busy.idle': 'Rảnh',
    'dashboard.message.none': 'Không có thông báo',
    'dashboard.sessionSource.codex': 'Codex',
    'dashboard.sessionSource.claude': 'Claude Code',
    'dashboard.sessionSource.gemini': 'Gemini CLI',
    'dashboard.sessionSource.codebuddy': 'CodeBuddy Code',
    'dashboard.sessionSource.all': 'Tất cả',
    'dashboard.sessionPath.all': 'Tất cả đường dẫn',
    'dashboard.sessionQuery.unsupported': 'Nguồn hiện tại không hỗ trợ',
    'dashboard.sessionQuery.unset': 'Chưa đặt',
    'dashboard.healthStatus.failRead': 'Đọc thất bại',
    'dashboard.healthStatus.initializing': 'Đang khởi tạo',
    'dashboard.healthStatus.ok': 'Bình thường',
    'dashboard.modelStatus.loading': 'Đang tải',
    'dashboard.modelStatus.error': 'Lỗi tải',
    'dashboard.modelStatus.ok': 'Bình thường',
    'dashboard.health.ok': 'Kiểm tra đạt',
    'dashboard.health.fail': 'Kiểm tra thất bại',
    'dashboard.health.issues': '{count} vấn đề',
    'dashboard.issues.title': 'Phát hiện {count} vấn đề cần xử lý',
    'dashboard.state.loading': 'Đang tải',
    'dashboard.state.ready': 'Sẵn sàng',
    'dashboard.state.idle': 'Chưa tải',
    'dashboard.none': 'Không có',
    'dashboard.sessions.count': '{count} phiên',
    'dashboard.usage.range': 'Phạm vi {value}',
    'dashboard.tasks.queue': 'chạy {running} / hàng chờ {queued}',
    'dashboard.skills.count': 'đã cài {installed} / có thể nhập {importable}',
    'dashboard.providersHealth.title': 'Trạng thái Provider',
    'dashboard.providersHealth.current': '(hiện tại)',
    'dashboard.providersHealth.checking': 'Đang kiểm tra...',
    'dashboard.providersHealth.allOk': 'Tất cả Provider bình thường',
    'dashboard.providersHealth.hasIssues': '{count} Provider có vấn đề',

    // Plugins
    'plugins.sidebar.title': 'Plugins',
    'plugins.sidebar.note': 'Công cụ tiêu chuẩn có thể tái sử dụng. Plugin tùy chỉnh trong tương lai nên theo cùng cấu trúc.',
    'plugins.sidebar.ariaList': 'Danh sách plugin',
    'plugins.main.ariaWorkspace': 'Không gian làm việc plugin',
    'plugins.refresh': 'Làm mới',
    'plugins.refreshing': 'Đang làm mới...',
    'plugins.promptTemplates.title': 'Mẫu prompt',
    'plugins.promptTemplates.subtitle': 'Tích hợp: chỉnh chú thích mã ({{code}}). Sao chép rồi dán thẳng vào ô nhập.',
    'plugins.promptTemplates.mode.aria': 'Chế độ mẫu prompt',
    'plugins.promptTemplates.mode.compose': 'Tạo',
    'plugins.promptTemplates.mode.manage': 'Quản lý',
    'plugins.promptTemplates.compose.selectTemplate': 'Chọn mẫu',
    'plugins.promptTemplates.compose.chooseTemplate': 'Chọn mẫu',
    'plugins.promptTemplates.compose.chooseTemplateHint': 'Vui lòng chọn một mẫu để bắt đầu tạo.',
    'plugins.promptTemplates.compose.builtinSuffix': '(tích hợp)',
    'plugins.promptTemplates.compose.empty': 'Chưa có mẫu khả dụng.',
    'plugins.promptTemplates.compose.varsHint': 'Điền và thêm biến trong mục "Quản lý".',
    'plugins.promptTemplates.compose.missingCount': 'Còn thiếu {count} mục',
    'plugins.promptTemplates.compose.jumpToMissing': 'Chuyển đến mục thiếu',
    'plugins.promptTemplates.compose.goManage': 'Đến quản lý để điền biến',
    'plugins.promptTemplates.compose.outputTitle': 'Kết quả tạo',
    'plugins.promptTemplates.compose.outputHint': 'Nhấn "Sao chép" rồi dán thẳng vào ô nhập Codex/Claude.',
    'plugins.promptTemplates.compose.outputAria': 'Kết quả tạo (prompt)',
    'plugins.promptTemplates.compose.copy': 'Sao chép',
    'plugins.promptTemplates.manage.searchAria': 'Tìm kiếm mẫu',
    'plugins.promptTemplates.manage.searchPlaceholder': 'Tìm kiếm mẫu',
    'plugins.promptTemplates.manage.create': 'Tạo mới',
    'plugins.promptTemplates.manage.export': 'Xuất',
    'plugins.promptTemplates.manage.import': 'Nhập',
    'plugins.promptTemplates.manage.loading': 'Đang tải mẫu...',
    'plugins.promptTemplates.manage.empty': 'Chưa có mẫu.',
    'plugins.promptTemplates.manage.vars': '{count} biến',
    'plugins.promptTemplates.manage.builtin': 'tích hợp',
    'plugins.promptTemplates.manage.custom': 'tùy chỉnh',
    'plugins.promptTemplates.manage.newTemplateName': 'Mẫu mới',
    'plugins.promptTemplates.editor.selectHint': 'Vui lòng chọn một mẫu để chỉnh sửa.',
    'plugins.promptTemplates.editor.namePlaceholder': 'Tên mẫu',
    'plugins.promptTemplates.editor.nameAria': 'Tên mẫu',
    'plugins.promptTemplates.editor.duplicate': 'Nhân bản',
    'plugins.promptTemplates.editor.delete': 'Xóa',
    'plugins.promptTemplates.editor.save': 'Lưu',
    'plugins.promptTemplates.editor.builtinReadOnly': 'Mẫu tích hợp chỉ đọc, không hỗ trợ chỉnh sửa/lưu/xóa/nhân bản.',
    'plugins.promptTemplates.editor.descPlaceholder': 'Mô tả (tùy chọn)',
    'plugins.promptTemplates.editor.descAria': 'Mô tả mẫu',
    'plugins.promptTemplates.editor.templateLabel': 'Mẫu',
    'plugins.promptTemplates.editor.templateAria': 'Nội dung mẫu',
    'plugins.promptTemplates.editor.templatePlaceholder': 'Viết mẫu ở đây. Dùng {{var}} làm placeholder.',
    'plugins.promptTemplates.vars.title': 'Biến',
    'plugins.promptTemplates.vars.hint': 'Phát hiện từ mẫu. Điền để render prompt cuối cùng.',
    'plugins.promptTemplates.vars.reset': 'Đặt lại',
    'plugins.promptTemplates.vars.empty': 'Không phát hiện biến nào.',
    'plugins.promptTemplates.vars.valuePlaceholder': 'Giá trị biến: {name}',
    'plugins.promptTemplates.preview.title': 'Xem trước',
    'plugins.promptTemplates.preview.hint': 'Kết quả render (biến thiếu sẽ thay bằng rỗng).',
    'plugins.promptTemplates.preview.copy': 'Sao chép',
    'plugins.promptTemplates.preview.outputAria': 'Kết quả render (prompt)',
    'plugins.promptTemplates.noPluginSelected': 'Vui lòng chọn một plugin từ bên trái.',
    'plugins.meta.attribution': 'Tạo bởi: {createdBy} · Duy trì bởi: {maintainers}',
    'plugins.meta.createdBy': 'Tạo bởi: {createdBy}',
    'plugins.meta.maintainedBy': 'Duy trì bởi: {maintainers}',

    // Toast
    'toast.export.empty': 'Không có nội dung để xuất',
    'toast.export.ok': 'Đã xuất',
    'toast.export.fail': 'Xuất thất bại',
    'toast.import.ok': 'Nhập thành công',
    'toast.import.fail': 'Nhập thất bại',
    'toast.import.notAvailable': 'Nhập không khả dụng',
    'toast.import.readFileFail': 'Đọc tệp thất bại',
    'toast.import.invalidJson': 'JSON không hợp lệ',
    'toast.import.expectedArray': 'JSON phải là mảng',
    'toast.export.notSupported': 'Hiện không hỗ trợ xuất',
    'toast.plugins.loadFail': 'Tải Plugins thất bại',
    'toast.templates.builtinNotEditable': 'Mẫu tích hợp không thể chỉnh sửa',
    'toast.templates.builtinNotModifiable': 'Mẫu tích hợp không thể sửa đổi, hãy nhân bản trước khi chỉnh sửa',
    'toast.templates.nameRequired': 'Tên mẫu không được để trống',
    'toast.templates.builtinNotDuplicable': 'Mẫu tích hợp không thể nhân bản',
    'toast.templates.builtinNotDeletable': 'Mẫu tích hợp không thể xóa',
    'toast.templates.deleteTitle': 'Xóa mẫu',
    'toast.templates.deleteMessage': 'Xóa "{name}"? Thao tác này không thể hoàn tác.',
    'toast.templates.deleteConfirm': 'Xóa',
    'toast.templates.deleteCancel': 'Hủy',

    // Modals
    'modal.providerAdd.title': 'Thêm nhà cung cấp',
    'modal.providerEdit.title': 'Chỉnh sửa nhà cung cấp',
    'modal.modelAdd.title': 'Thêm mô hình',
    'modal.modelManage.title': 'Quản lý mô hình',
    'modal.claudeConfigAdd.title': 'Thêm cấu hình Claude Code',
    'modal.claudeConfigEdit.title': 'Chỉnh sửa cấu hình Claude Code',
    'modal.configTemplate.label': 'Mẫu config.toml',
    'modal.configTemplate.mode.twoStep': 'Xác nhận hai bước: xem trước sự khác biệt, sau đó áp dụng.',
    'modal.configTemplate.mode.oneStep': 'Áp dụng một bước: nhấn "Áp dụng" để ghi trực tiếp.',
    'modal.configTemplate.title': 'Trình soạn thảo mẫu Config (xác nhận thủ công trước khi áp dụng)',
    'modal.configTemplate.placeholder': 'Chỉnh sửa nội dung mẫu config.toml tại đây',
    'modal.agents.export': 'Xuất',
    'modal.agents.copy': 'Sao chép',
    'modal.agents.title': 'Trình soạn thảo AGENTS.md',
    'modal.agents.hint': 'Sau khi lưu sẽ ghi vào AGENTS.md đích (cùng cấp với config.toml).',
    'modal.agents.targetFile': 'Tệp đích',
    'modal.agents.contentLabel': 'Nội dung AGENTS.md',
    'modal.agents.placeholder': 'Chỉnh sửa nội dung AGENTS.md tại đây',
    'modal.agents.unsaved.previewModeHint': 'Chế độ xem trước: thay đổi hiện tại chưa lưu, chỉ ghi vào tệp khi nhấn "Áp dụng".',
    'modal.agents.unsaved.detectedHint': 'Phát hiện thay đổi chưa lưu: hãy lưu trước khi đóng trang hoặc áp dụng.',
    'modal.agents.hint.shortcuts': 'Phím tắt: Esc (trở về chỉnh sửa khi xem trước, đóng cửa sổ khi đang chỉnh sửa).',
    'modal.agents.hint.twoStepSave': 'Lưu cần hai bước: nhấn "Xác nhận" để xem trước sự khác biệt, sau đó nhấn "Áp dụng".',
    'modal.agents.title.default': 'Trình soạn thảo AGENTS.md',
    'modal.agents.title.claudeMd': 'Trình soạn thảo CLAUDE.md',
    'modal.agents.title.openclaw': 'Trình soạn thảo AGENTS.md OpenClaw',
    'modal.agents.hint.default': 'Sau khi lưu sẽ ghi vào AGENTS.md đích (cùng cấp với config.toml).',
    'modal.agents.hint.claudeMd': 'Sau khi lưu sẽ ghi vào ~/.claude/CLAUDE.md.',
    'modal.agents.contentLabel.claudeMd': 'Nội dung CLAUDE.md',
    'modal.agents.placeholder.claudeMd': 'Chỉnh sửa nội dung CLAUDE.md tại đây',
    'modal.agents.hint.openclaw': 'Sau khi lưu sẽ ghi vào AGENTS.md trong OpenClaw Workspace.',
    'modal.agents.title.openclawWorkspaceFile': 'Tệp không gian làm việc OpenClaw: {fileName}',
    'modal.agents.hint.openclawWorkspaceFile': 'Sau khi lưu sẽ ghi vào {fileName} trong OpenClaw Workspace.',
    'modal.skills.title': 'Quản lý Skills',
    'modal.skills.subtitle': 'Quản lý Skills cục bộ của máy chủ hiện tại.',
    'modal.skills.target.aria': 'Chọn mục tiêu quản lý Skills',
    'modal.skills.rootDir': 'Thư mục Skills ({label})',
    'modal.skills.summary.target': 'Mục tiêu cài đặt',
    'modal.skills.summary.total': 'Tổng cục bộ',
    'modal.skills.summary.withSkill': 'Có SKILL.md',
    'modal.skills.summary.missingSkill': 'Thiếu SKILL.md',
    'modal.skills.summary.importable': 'Có thể nhập',
    'modal.skills.panel.aria': 'Bảng quản lý Skills',
    'modal.skills.local.title': 'Skills cục bộ',
    'modal.skills.local.note': 'Có thể tìm kiếm, lọc và xóa hàng loạt.',
    'modal.skills.filter.keywordAria': 'Lọc skill theo tên hoặc mô tả',
    'modal.skills.filter.keywordPlaceholder': 'Tìm theo tên thư mục/tên hiển thị/mô tả',
    'modal.skills.filter.statusAria': 'Lọc skill theo trạng thái SKILL.md',
    'modal.skills.filter.status.all': 'Tất cả trạng thái',
    'modal.skills.filter.status.withSkill': 'Chỉ có SKILL.md',
    'modal.skills.filter.status.missingSkill': 'Chỉ thiếu SKILL.md',
    'modal.skills.selection.stats': 'Đã chọn {selected} (lọc được {filtered}/{total}, đã chọn trong lọc {visibleSelected})',
    'modal.skills.empty.local': 'Chưa có skill nào để quản lý.',
    'modal.skills.empty.filtered': 'Không có skill nào khớp với điều kiện lọc hiện tại.',
    'modal.skills.pill.hasSkillFile': 'Có SKILL.md',
    'modal.skills.pill.missingSkillFile': 'Thiếu SKILL.md',
    'modal.skills.pill.symlink': 'Liên kết tượng trưng',
    'modal.skills.pill.dir': 'Thư mục',
    'modal.skills.import.title': 'Nhập liên ứng dụng',
    'modal.skills.import.note': 'Quét và nhập vào {label} hiện tại.',
    'modal.skills.import.scan': 'Quét có thể nhập',
    'modal.skills.import.stats': 'Đã chọn {selected}/{total}, có SKILL.md {configured}, thiếu {missing}',
    'modal.skills.import.emptyHint': 'Chưa có skill nào có thể nhập, hãy nhấn "Quét có thể nhập".',
    'modal.skills.bulk.title': 'Thao tác hàng loạt',
    'modal.skills.bulk.note': 'Bên phải là thao tác nhập, bên trái là chọn cục bộ.',
    'modal.skills.actions.zipImport': 'Nhập ZIP',
    'modal.skills.actions.zipImporting': 'Đang nhập ZIP...',
    'modal.skills.actions.exportSelected': 'Xuất đã chọn',
    'modal.skills.actions.exporting': 'Đang xuất...',
    'modal.skills.actions.importSelected': 'Nhập đã chọn',
    'modal.skills.actions.importing': 'Đang nhập...',
    'modal.skills.actions.deleteSelected': 'Xóa đã chọn',
    'modal.skills.actions.deleting': 'Đang xóa...',
    'modal.openclaw.loadCurrent': 'Tải cấu hình hiện tại',
    'modal.openclaw.quick.title': 'Cấu hình nhanh cho người mới',
    'modal.openclaw.quick.readFromEditor': 'Đọc từ trình soạn thảo',
    'modal.openclaw.quick.step1': 'Điền Provider và mô hình',
    'modal.openclaw.quick.step3': 'Lưu và áp dụng',
    'modal.openclaw.quick.providerHint': 'Sẽ ghép thành provider/model làm ID mô hình chính.',
    'modal.openclaw.quick.baseUrlHintDefault': 'Đã điền sẵn giá trị mặc định của provider tích hợp OpenClaw, có thể sửa trực tiếp.',
    'modal.openclaw.quick.baseUrlHintReadonly': 'Phát hiện tham chiếu ngoài, chỉ đọc trong form nhanh; để sửa hãy dùng trình soạn thảo gốc.',
    'modal.openclaw.quick.apiKeyHintFromAuth': 'Giá trị hiện tại từ cấu hình xác thực ngoài của OpenClaw; khi sửa và "Lưu & áp dụng" sẽ ghi lại vào auth profile tương ứng.',
    'modal.openclaw.quick.apiKeyHintReadonly': 'Phát hiện xác thực ngoài hoặc tham chiếu, chỉ đọc trong form nhanh; để sửa hãy dùng trình soạn thảo gốc hoặc cấu hình xác thực tương ứng.',
    'modal.openclaw.quick.apiKeyHintKeep': 'Để trống nghĩa là không ghi đè key hiện tại.',
    'modal.openclaw.quick.modelTitle': 'Mô hình',
    'modal.openclaw.quick.optionsTitle': 'Tùy chọn',
    'modal.openclaw.quick.setPrimary': 'Đặt làm mô hình chính',
    'modal.openclaw.quick.overrideProvider': 'Ghi đè thông tin cơ bản Provider cùng tên',
    'modal.openclaw.quick.overrideModels': 'Ghi đè danh sách mô hình cùng tên',
    'modal.openclaw.quick.optionsHint': 'Tắt ghi đè sẽ chỉ bổ sung các trường còn trống.',
    'modal.openclaw.quick.writeToEditor': 'Ghi vào trình soạn thảo',
    'modal.openclaw.quick.subtitle': 'Hoàn thành theo 3 bước: điền Provider và mô hình, ghi vào trình soạn thảo, lưu và áp dụng.',
    'modal.openclaw.quick.step2': 'Nhấn ghi vào trình soạn thảo',
    'modal.openclaw.structured.writeHint': 'Ghi vào trình soạn thảo sẽ sắp xếp lại JSON, chú thích có thể bị mất.',

    // Diff
    'diff.title.configTemplate': 'Xem trước thay đổi (config.toml)',
    'diff.generating': 'Đang tạo...',
    'diff.failed': 'Tạo thất bại',
    'diff.noChanges': 'Không phát hiện thay đổi nào',
    'diff.hint.busy': 'Đang tạo sự khác biệt hoặc đang áp dụng, thao tác tạm thời không khả dụng.',
    'diff.hint.failedBack': 'Xem trước thay đổi thất bại, hãy quay lại chỉnh sửa và thử lại.',
    'diff.hint.noChangesBack': 'Không phát hiện thay đổi, có thể quay lại tiếp tục chỉnh sửa hoặc hủy.',
    'diff.hint.previewMode': 'Đang ở chế độ xem trước, nhấn "Áp dụng" để ghi hoặc "Quay lại chỉnh sửa".',
    'diff.tooLargeSkip': 'Nội dung quá lớn, đã bỏ qua xem trước từng dòng',
    'diff.viewHint.preview': 'Đang ở chế độ xem trước, nhấn "Áp dụng" để lưu hoặc "Quay lại chỉnh sửa".',
    'diff.viewHint.truncated': 'Nội dung quá lớn, đã bỏ qua xem trước, nhấn "Áp dụng" để lưu hoặc "Quay lại chỉnh sửa".',

    // Docs
    'docs.title': 'Tài liệu cài đặt CLI',
    'docs.subtitle': 'Xem lệnh Claude Code / Gemini CLI / CodeBuddy Code / Codex CLI.',
    'docs.section.commands': 'Lệnh cài đặt',
    'docs.section.commandsNote': 'Lệnh có thể sao chép trực tiếp.',
    'docs.section.faq': 'Câu hỏi thường gặp',
    'docs.section.faqNote': 'Xem câu hỏi thường gặp bên dưới.',
    'docs.command.aria': 'Lệnh {name}',
    'docs.registryHintPrefix': 'Lệnh sẽ thêm:',
    'docs.registryHintCustom': 'Nhập URL đầy đủ (bao gồm http/https), sẽ tự động thêm vào lệnh.',
    'docs.registry.tencent': 'Tencent Cloud',
    'docs.meta.bin': 'bin: {bin}',
    'docs.termuxLabel': 'Termux',
    'docs.termuxAria': 'Termux Codex CLI command',
    'docs.rule.1': 'Lệnh được tạo theo trình quản lý gói, registry và thao tác hiện tại.',
    'docs.rule.2': 'Registry tùy chỉnh chỉ dùng cho cài đặt và nâng cấp.',
    'docs.tip.win.1': 'Khi PowerShell báo thiếu quyền (EACCES/EPERM), hãy chạy lệnh cài đặt với quyền quản trị viên.',
    'docs.tip.win.2': 'Sau khi cài đặt nếu vẫn báo không tìm thấy lệnh, hãy mở terminal mới và chạy: where codex / where claude / where gemini / where codebuddy.',
    'docs.tip.win.3': 'Khi mạng công ty bị hạn chế, hãy chuyển sang registry khác (npmmirror / Tencent Cloud / tùy chỉnh).',
    'docs.tip.unix.1': 'Khi gặp lỗi quyền EACCES, ưu tiên sửa quyền thư mục global Node, không nên dùng sudo npm trực tiếp.',
    'docs.tip.unix.2': 'Sau khi cài đặt nếu lệnh chưa hoạt động, hãy mở terminal mới và chạy: which codex / which claude / which gemini / which codebuddy.',
    'docs.tip.unix.3': 'Khi mạng công ty bị hạn chế, hãy chuyển sang registry khác (npmmirror / Tencent Cloud / tùy chỉnh).',

    // Sessions
    'sessions.loading': 'Đang tải...',
    'sessions.sourceTitle': 'Nguồn phiên',
    'sessions.refresh': 'Làm mới phiên',
    'sessions.refreshing': 'Đang làm mới...',
    'sessions.allPaths': 'Tất cả đường dẫn',
    'sessions.source.codex': 'Codex',
    'sessions.source.claudeCode': 'Claude Code',
    'sessions.source.gemini': 'Gemini CLI',
    'sessions.source.codebuddy': 'CodeBuddy Code',
    'sessions.loadingList': 'Đang tải phiên...',
    'sessions.empty': 'Chưa có lịch sử phiên',
    'sessions.unknownTime': 'Thời gian không rõ',
    'sessions.query.placeholder.enabled': 'Tìm kiếm từ khóa (hỗ trợ Codex/Claude/Gemini/CodeBuddy, ví dụ: claude code)',
    'sessions.query.placeholder.disabled': 'Nguồn hiện tại chưa hỗ trợ tìm kiếm từ khóa',
    'sessions.pin': 'Ghim',
    'sessions.unpin': 'Bỏ ghim',
    'sessions.copyResume': 'Sao chép lệnh tiếp tục',
    'sessions.preview.refresh': 'Làm mới nội dung',
    'sessions.preview.loading': 'Đang tải...',
    'sessions.preview.deleteHard': 'Xóa trực tiếp',
    'sessions.preview.moveToTrash': 'Chuyển vào thùng rác',
    'sessions.preview.deleting': 'Đang xóa...',
    'sessions.preview.moving': 'Đang chuyển...',
    'sessions.preview.export': 'Xuất lịch sử',
    'sessions.preview.exporting': 'Đang xuất...',
    'sessions.preview.convert': 'Tạo phiên phái sinh',
    'sessions.preview.converting': 'Đang tạo...',
    'sessions.preview.convert.loadedOnly': 'Chỉ chuyển đổi tin nhắn đã tải',
    'sessions.preview.importNative': 'Nhập thư mục gốc',
    'sessions.preview.importingNative': 'Đang nhập...',
    'sessions.preview.importNative.unsupported': 'Không hỗ trợ thao tác này',
    'sessions.preview.importNative.confirmTitle': 'Ghi đè tệp phiên gốc?',
    'sessions.preview.importNative.confirmMessage': 'Tệp phiên gốc đã tồn tại, ghi đè sẽ thay thế phiên cùng tên trong thư mục gốc của công cụ đích.',
    'sessions.preview.importNative.confirmText': 'Ghi đè',
    'sessions.preview.importNative.cancelled': 'Đã hủy nhập',
    'sessions.preview.importNative.conflict': 'Phiên gốc đã tồn tại',
    'sessions.preview.importNative.invalidSource': 'Nguồn phiên không hợp lệ',
    'sessions.preview.importNative.fileNotFound': 'Không tìm thấy tệp phiên',
    'sessions.preview.importNative.nativePathUnavailable': 'Không thể phân giải đường dẫn phiên gốc',
    'sessions.preview.importNative.success': 'Đã nhập vào thư mục gốc',
    'sessions.preview.importNative.failed': 'Nhập thất bại',
    'sessions.preview.importNative.failedWithReason': 'Nhập thư mục gốc thất bại: {reason}',
    'sessions.preview.copyLink': 'Sao chép liên kết',
    'sessions.preview.copyPath': 'Sao chép đường dẫn',
    'sessions.preview.loadingBody': 'Đang tải nội dung phiên...',
    'sessions.preview.emptyMsgs': 'Phiên hiện tại chưa có tin nhắn nào để hiển thị',
    'sessions.preview.rendering': 'Đang render nội dung phiên...',
    'sessions.preview.rerender': 'Render lại',
    'sessions.preview.preparing': 'Đang chuẩn bị nội dung phiên...',
    'sessions.preview.clipped': 'Chỉ hiển thị {count} tin nhắn gần nhất.',
    'sessions.preview.shownCount': 'Đã hiển thị {shown}/{total}',
    'sessions.preview.loadMore': 'Tải thêm (còn {remain})',
    'sessions.preview.loadingMore': 'Đang tải tin nhắn cũ hơn...',
    'sessions.timeline.aria': 'Dòng thời gian phiên',
    'sessions.selectHint': 'Vui lòng chọn một phiên ở bên trái',
    'sessions.role.all': 'Tất cả vai trò',
    'sessions.role.user': 'Chỉ User',
    'sessions.role.assistant': 'Chỉ Assistant',
    'sessions.role.system': 'Chỉ System',
    'sessions.time.all': 'Tất cả thời gian',
    'sessions.time.7d': '7 ngày gần đây',
    'sessions.time.30d': '30 ngày gần đây',
    'sessions.time.90d': '90 ngày gần đây',
    'sessions.sort.time': 'Theo thời gian',
    'sessions.sort.hot': 'Theo mức độ',
    'sessions.sort.hotBadge': 'Nóng',
    'sessions.filters.copyLink': 'Sao chép liên kết lọc',
    'sessions.filters.urlBuildFail': 'Không thể tạo liên kết',
    'sessions.filters.source': 'Nguồn',
    'sessions.filters.path': 'Đường dẫn',
    'sessions.filters.keyword': 'Từ khóa',
    'sessions.filters.role': 'Vai trò',
    'sessions.filters.time': 'Thời gian',
    'sessions.roleLabel.user': 'User',
    'sessions.roleLabel.system': 'System',
    'sessions.roleLabel.assistant': 'Assistant',
    'sessions.sourceLabel': 'Nguồn: {value}',
    'sessions.source.all': 'Tất cả',

    // Usage
    'usage.overview': 'Tổng quan Usage',
    'usage.range.aria': 'Phạm vi thời gian Usage',
    'usage.range.7d': '7 ngày gần đây',
    'usage.range.30d': '30 ngày gần đây',
    'usage.compare.toggle': 'So sánh kỳ trước',
    'usage.compare.prev': 'Kỳ trước',
    'usage.compare.delta': 'Thay đổi',
    'usage.refresh': 'Làm mới thống kê',
    'usage.refreshing': 'Đang làm mới...',
    'usage.loading': 'Đang tải thống kê Usage...',
    'usage.empty': 'Chưa có dữ liệu phiên để thống kê',
    'usage.refreshOverlay': 'Đang làm mới…',
    'usage.copyTitle': 'Nhấn để sao chép: {value}',
    'usage.copySuccess': 'Đã sao chép: {label}',
    'usage.copyFail': 'Sao chép thất bại',
    'usage.copyNone': 'Không có nội dung để sao chép',
    'usage.daily.title': 'Tiêu thụ mỗi ngày',
    'usage.daily.subtitle': 'Tổng hợp token và chi phí ước tính theo ngày (chi phí hiển thị theo giá trị tối đa).',
    'usage.daily.note': 'Lưu ý: chi phí ước tính mặc định không bao gồm Claude; chỉ tính khi khớp được đơn giá mô hình và phiên có token input/output.',
    'usage.heatmap.title': 'Bản đồ nhiệt hoạt động',
    'usage.heatmap.subtitle': 'Tổng hợp theo số phiên mỗi ngày, hover để xem dữ liệu chi tiết.',
    'usage.heatmap.legend.less': 'Ít',
    'usage.heatmap.legend.more': 'Nhiều',
    'usage.heatmap.tooltip': '{date} · {sessions} phiên · {messages} tin nhắn · {tokens} token',
    'usage.heatmap.aria': '{date}, {sessions} phiên',
    'usage.hourlyHeatmap.title': 'Bản đồ nhiệt hoạt động 7×24',
    'usage.hourlyHeatmap.subtitle': 'Tổng hợp phân phối phiên theo thứ × giờ, màu đậm = hoạt động cao.',
    'usage.hourlyHeatmap.tooltip': '{weekday} {hour}:00 · {sessions} phiên · {messages} tin nhắn · {tokens} token',
    'usage.hourlyHeatmap.legend.less': 'Ít',
    'usage.hourlyHeatmap.legend.more': 'Nhiều',
    'usage.legend.tokens': 'Token',
    'usage.legend.cost': 'Chi phí ước tính',
    'usage.table.date': 'Ngày',
    'usage.table.sessions': 'Phiên',
    'usage.table.messages': 'Tin nhắn',
    'usage.table.tokens': 'Token',
    'usage.table.cost': 'Chi phí ước tính',
    'usage.trend.sessions': 'Xu hướng phiên',
    'usage.trend.messages': 'Xu hướng tin nhắn',
    'usage.trend.activeHours': 'Khung giờ hoạt động',
    'usage.trend.sources': 'Phân tích nguồn',
    'usage.legend.codex': 'Codex',
    'usage.legend.claude': 'Claude',
    'usage.trend.sessions.codexTitle': 'Codex {count}',
    'usage.trend.sessions.claudeTitle': 'Claude {count}',
    'usage.trend.messages.barTitle': '{count} tin nhắn',
    'usage.hour.title': '{hour}:00 · {count} phiên',
    'usage.source.row': '{sessions} phiên · {messages} tin nhắn · trung bình {avg}',
    'usage.summary.sessions': 'Tổng phiên',
    'usage.summary.messages': 'Tổng tin nhắn',
    'usage.summary.tokens': 'Tổng Token',
    'usage.summary.contextWindow': 'Tổng ngữ cảnh',
    'usage.summary.estimatedCost': 'Chi phí ước tính · {range}',
    'usage.estimatedCost.note.excludesClaudePrefix': 'Chưa bao gồm Claude, ',
    'usage.estimatedCost.method.configured': 'Ước tính theo đơn giá đã cấu hình',
    'usage.estimatedCost.method.catalog': 'Ước tính theo danh mục mô hình công khai',
    'usage.estimatedCost.method.configuredAndCatalog': 'Ước tính theo đơn giá đã cấu hình + danh mục công khai',
    'usage.estimatedCost.detail.estimate': '{prefix}{method}, ước tính {estimate}, bao phủ {covered}/{total} phiên, khoảng {percent}% token',
    'usage.estimatedCost.detail.missing': '{prefix}Thiếu đơn giá mô hình khớp hoặc phân tách token. Hãy bổ sung models.cost hoặc đảm bảo phiên đã ghi token input/output.',
    'usage.summary.activeDuration': 'Thời gian hoạt động',
    'usage.summary.activeDuration.title': 'Tổng khoảng thời gian phiên {value}',
    'usage.summary.totalDuration': 'Tổng thời gian',
    'usage.summary.totalDuration.title': 'Khoảng thời gian tổng thể {value}',
    'usage.summary.activeDays': 'Ngày hoạt động',
    'usage.summary.avgMessagesPerSession': 'Tin nhắn trung bình mỗi phiên',
    'usage.summary.busiestDay': 'Ngày bận nhất',
    'usage.summary.busiestHour': 'Khung giờ cao điểm',
    'usage.currentSession.title': 'Phiên hiện tại',
    'usage.currentSession.apiDuration': 'Thời gian API',
    'usage.currentSession.totalDuration': 'Tổng thời gian',
    'usage.currentSession.tokens': 'Token',
    'usage.range.kicker.all': 'Tất cả',
    'usage.range.kicker.30d': '30 ngày gần đây',
    'usage.range.kicker.7d': '7 ngày gần đây',
    'usage.copyTokenDay': 'Đã sao chép: Token ({day})',
    'usage.copyCostDay': 'Đã sao chép: Chi phí ước tính ({day})',
    'usage.dayDetail.title': 'Chi tiết {day}',
    'usage.dayDetail.subtitle': 'Chọn ngày để xem nhanh cấu thành trong ngày.',
    'usage.dayDetail.pick': 'Chọn ngày',
    'usage.dayDetail.empty': 'Vui lòng chọn một ngày để xem cấu thành trong ngày.',
    'usage.dayDetail.clear': 'Xóa',
    'usage.dayDetail.topSessions': 'Top phiên',
    'usage.dayDetail.topModels': 'Top mô hình',
    'usage.models.title': 'Mô hình đã dùng',
    'usage.models.subtitle': 'Chỉ liệt kê tên mô hình thực sự được ghi.',
    'usage.models.kicker': 'Đã nhận diện {modeled}/{total}',
    'usage.models.count': 'Số mô hình',
    'usage.models.coverage': 'Tỷ lệ phủ phiên',
    'usage.models.missing': 'Thiếu mô hình',
    'usage.models.noneTitle': 'Không đọc được tên mô hình trong phạm vi hiện tại',
    'usage.models.noneBody': 'Đã quét {total} phiên nhưng không tìm thấy trường model nhận diện được trong bản ghi gốc.',
    'usage.models.providerOnly': 'Trong đó {count} phiên cũ chỉ ghi provider.',
    'usage.models.missingNote.providerOnly': 'Ngoài ra {count} phiên không ghi tên mô hình, chưa tính vào danh sách.',
    'usage.models.missingNote': 'Ngoài ra {count} phiên thiếu mô hình, chưa tính vào danh sách.',
    'usage.models.missingListTitle': 'Phiên vẫn thiếu tên mô hình',
    'usage.models.chipTitle': '{model} · {sessions} phiên · {messages} tin nhắn{tokens}',
    'usage.models.meta': '{sessions} phiên · {messages} tin nhắn{tokens}',
    'usage.weekday.title': 'Phân phối theo ngày trong tuần',
    'usage.paths.title': 'Đường dẫn thường dùng',
    'usage.paths.empty': 'Chưa có dữ liệu đường dẫn',
    'usage.paths.count': '{count} lần',
    'usage.paths.meta': '{messages} tin nhắn{recent}',
    'usage.paths.recent': ' · Gần đây {label}',
    'usage.recent.title': 'Phiên hoạt động gần đây',
    'usage.sessions.empty': 'Chưa có dữ liệu phiên',
    'usage.sessions.messages': '{count} tin nhắn',
    'usage.sessions.topDensity': 'Mật độ tin nhắn cao nhất',
    'usage.rangeLabel': 'Phạm vi: {value}',
    'usage.range.all': 'Tất cả',
    'usage.range.7d.short': '7 ngày gần đây',
    'usage.range.30d.short': '30 ngày gần đây',

    // Config
    'config.addProvider': 'Thêm nhà cung cấp',
    'config.providerTemplate.title': 'Nhà cung cấp đặt sẵn',
    'config.models': 'Mô hình',
    'config.modelLoading': 'Đang tải...',
    'config.models.unlimited': 'Hiện chưa có danh sách mô hình, có thể nhập tay.',
    'config.models.error': 'Lấy danh sách mô hình thất bại, có thể nhập tay.',
    'config.models.notInList.codex': 'Mô hình hiện tại không có trong danh sách, có thể nhập tay hoặc đổi mẫu.',
    'config.models.notInList.other': 'Mô hình hiện tại không có trong danh sách, có thể nhập tay.',
    'config.template.editFirst': 'Sửa mẫu trước, sau đó áp dụng.',
    'config.template.bridgeCodexOnly': '{hint} Mẫu chỉ dành cho Codex chỉnh sửa.',
    'config.template.openEditor': 'Mở trình soạn thảo mẫu',
    'config.serviceTier': 'Cấp dịch vụ',
    'config.serviceTier.fast': 'fast (mặc định)',
    'config.serviceTier.standard': 'standard',
    'config.serviceTier.hint': 'Chỉ fast ghi {field}.',
    'config.reasoningEffort': 'Cường độ suy luận',
    'config.reasoningEffort.medium': 'medium (mặc định)',
    'config.reasoningEffort.hint': 'Kiểm soát độ sâu suy luận; high sâu hơn.',
    'config.contextBudget': 'Ngưỡng nén',
    'config.reset': 'Đặt lại',
    'config.example': 'Ví dụ: {value}',
    'config.contextWindow.hint': 'Giới hạn ngữ cảnh, mặc định 190000.',
    'config.autoCompact.hint': 'Ngưỡng nén tự động, mặc định 185000.',
    'config.agents.open': 'Mở AGENTS.md',
    'config.url.unset': 'Chưa đặt URL',
    'config.model.unset': 'Chưa đặt mô hình',
    'config.badge.system': 'Hệ thống',
    'config.availabilityTest': 'Kiểm tra khả dụng',
    'config.availabilityTestAria': 'Kiểm tra khả dụng {name}',
    'config.health.title': 'Kiểm tra sức khỏe cấu hình',
    'config.health.run': 'Chạy kiểm tra',
    'config.health.running': 'Đang kiểm tra...',
    'config.health.hint': 'Sẽ kiểm tra khả dụng của tất cả nhà cung cấp hàng loạt và làm mới hiển thị độ trễ.',
    'config.health.progress': 'Đã xong {done}/{total} · Thất bại {failed}',
    'config.health.ok': 'Kiểm tra đạt',
    'config.health.fail': 'Kiểm tra chưa đạt',
    'config.health.issues': '{count} vấn đề',
    'config.shareCommand': 'Chia sẻ lệnh',
    'config.shareDisabled': 'Không thể chia sẻ',
    'config.shareCommand.aria': 'Chia sẻ lệnh nhập',
    'config.provider.edit.aria': 'Chỉnh sửa nhà cung cấp: {name}',
    'config.provider.delete.aria': 'Xóa nhà cung cấp: {name}',
    'config.provider.clone': 'Nhân bản',
    'config.provider.clone.aria': 'Nhân bản nhà cung cấp: {name}',
    'app.loadingConfig': 'Đang tải cấu hình...',
    'common.current': 'Hiện tại {value}',
    'common.readFromEditor': 'Đọc từ trình soạn thảo',

    // Orchestration
    'orchestration.queueStats': 'Hàng chờ {running} đang chạy · {queued} đang chờ',
    'orchestration.hero.kicker': 'Điều phối tác vụ',
    'orchestration.hero.title': 'Chia nhu cầu thành các bước thực thi được',
    'orchestration.hero.subtitle': 'Viết mục tiêu trước, xem trước kế hoạch, rồi thực thi.',
    'orchestration.draft.reset': 'Đặt lại bản nháp',
    'orchestration.summary.aria': 'Tổng quan điều phối tác vụ',
    'orchestration.summary.running': 'Đang chạy',
    'orchestration.summary.queued': 'Đang xếp hàng',
    'orchestration.summary.runs': 'Lịch sử chạy',
    'orchestration.step1.title': 'Viết rõ kết quả trước',
    'orchestration.step1.subtitle': 'Chỉ viết những gì ảnh hưởng đến việc thực thi.',
    'orchestration.templates.title': 'Ví dụ nhanh',
    'orchestration.templates.reviewFix.label': 'Sửa review + hồi quy',
    'orchestration.templates.reviewFix.target': 'Sửa các bình luận review PR hiện tại và bổ sung test hồi quy tương ứng',
    'orchestration.templates.reviewFix.notes': 'Không thay đổi module không liên quan; cần cung cấp kết quả xác minh',
    'orchestration.templates.reviewFix.followUps': 'Tiếp tục xử lý bình luận review mới\nCuối cùng cập nhật tóm tắt PR',
    'orchestration.templates.planOnly.label': 'Chỉ lập kế hoạch khảo sát',
    'orchestration.templates.planOnly.target': 'Khảo sát nguyên nhân gốc rễ và đưa ra kế hoạch thực thi, không sửa code trực tiếp',
    'orchestration.templates.planOnly.notes': 'Ưu tiên xác định nguyên nhân gốc rễ, phạm vi ảnh hưởng và điểm rủi ro',
    'orchestration.templates.workflowBatch.label': 'Xử lý hàng loạt Workflow',
    'orchestration.templates.workflowBatch.target': 'Dùng Workflow chạy một bộ kiểm tra cố định và tổng hợp kết quả',
    'orchestration.templates.workflowBatch.workflowIds': 'diagnose-config\nsafe-provider-switch',
    'orchestration.templates.workflowBatch.notes': 'Đưa ra kết luận thống nhất, tránh mô tả trùng lặp',
    'orchestration.fields.target': 'Mục tiêu',
    'orchestration.fields.target.placeholder': 'Ví dụ: Sửa các bình luận review PR hiện tại và bổ sung test hồi quy; không thay đổi module không liên quan',
    'orchestration.fields.target.hint': 'Một câu mô tả rõ kết quả, ranh giới và tiêu chí nghiệm thu là đủ.',
    'orchestration.engine.codex': 'Codex',
    'orchestration.engine.workflow': 'Workflow',
    'orchestration.runMode.write': 'Ghi',
    'orchestration.runMode.readOnly': 'Chỉ đọc',
    'orchestration.runMode.dryRun': 'Chỉ diễn tập',
    'orchestration.pills.hasTitle': 'Đã có tiêu đề',
    'orchestration.pills.workflowCount': 'Workflow {count}',
    'orchestration.pills.planNodes': 'Kế hoạch {count} nút',
    'orchestration.step2.title': 'Chọn phương thức thực thi',
    'orchestration.step2.subtitle': 'Mục thường dùng mặc định mở rộng, phần còn lại đặt trong cài đặt nâng cao.',
    'orchestration.fields.engine': 'Động cơ',
    'orchestration.fields.runMode': 'Chế độ chạy',
    'orchestration.advanced.title': 'Cài đặt nâng cao',
    'orchestration.fields.title': 'Tiêu đề',
    'orchestration.fields.title.placeholder': 'Tùy chọn, mặc định tự động trích từ mục tiêu',
    'orchestration.fields.notes': 'Ghi chú',
    'orchestration.fields.notes.placeholder': 'Ví dụ: Không viết lại kiến trúc hiện có, chỉ triển khai tăng dần',
    'orchestration.fields.notes.hint': 'Bổ sung ranh giới, vùng cấm, yêu cầu phong cách hoặc xác minh.',
    'orchestration.fields.followUps': 'Hành động tiếp theo (mỗi dòng một hành động)',
    'orchestration.fields.followUps.placeholder': 'Ví dụ:\nTiếp tục xử lý bình luận review\nCuối cùng bổ sung test hồi quy',
    'orchestration.fields.concurrency': 'Đồng thời',
    'orchestration.fields.concurrency.hint': 'Tác vụ phức tạp nên bắt đầu với 1~2 để ổn định hơn.',
    'orchestration.fields.autoFixRounds': 'Tự động sửa',
    'orchestration.fields.autoFixRounds.hint': 'Tự động thử lại vài vòng sau khi thất bại.',
    'orchestration.fields.workflowIds': 'Workflow ID (mỗi dòng một ID)',
    'orchestration.fields.workflowIds.placeholder': 'Ví dụ:\ndiagnose-config\nsafe-provider-switch',
    'orchestration.fields.workflowIds.hint': 'Chỉ cần trong chế độ Workflow. Hiện có {count} workflow khả dụng cục bộ.',
    'orchestration.workflow.stepCount': '{count} bước',
    'orchestration.step3.title': 'Xem trước trước, rồi thực thi',
    'orchestration.step3.subtitle': 'Xác nhận kế hoạch trước, rồi quyết định thực thi ngay hay xếp hàng.',
    'orchestration.actions.planning': 'Đang lập kế hoạch...',
    'orchestration.actions.previewOnly': 'Chỉ xem trước',
    'orchestration.actions.preparing': 'Đang chuẩn bị...',
    'orchestration.actions.generatePlan': 'Tạo kế hoạch',
    'orchestration.actions.planAndRun': 'Lập kế hoạch và thực thi',
    'orchestration.actions.processing': 'Đang xử lý...',
    'orchestration.actions.queueAndStart': 'Xếp hàng và bắt đầu',
    'orchestration.actions.caption': '"Lập kế hoạch và thực thi" sẽ tự động làm mới kế hoạch khi cần; dùng "Xếp hàng và bắt đầu" cho tác vụ hàng loạt.',
    'orchestration.stage.title': 'Mở không gian làm việc khi có nội dung',
    'orchestration.stage.subtitle': 'Viết mục tiêu trước, rồi xem trước kế hoạch.',
    'orchestration.stage.pill.target': 'Viết mục tiêu',
    'orchestration.stage.pill.preview': 'Xem trước',
    'orchestration.stage.pill.run': 'Thực thi hoặc xếp hàng',
    'orchestration.plan.title': 'Xem trước kế hoạch',
    'orchestration.plan.subtitle': 'Xác nhận nút, đợt và phụ thuộc trước.',
    'orchestration.plan.summary.nodes': 'Số nút',
    'orchestration.plan.summary.waves': 'Đợt',
    'orchestration.plan.summary.engine': 'Động cơ',
    'orchestration.plan.node.write': 'ghi',
    'orchestration.plan.node.readOnly': 'chỉ đọc',
    'orchestration.labels.dependencies': 'Phụ thuộc:',
    'orchestration.labels.error': 'Lỗi:',
    'orchestration.workbench.title': 'Bàn làm việc thực thi',
    'orchestration.workbench.subtitle': 'Chỉ mở rộng khi có nội dung.',
    'orchestration.queue.start': 'Bắt đầu hàng chờ',
    'orchestration.queue.starting': 'Đang khởi động...',
    'orchestration.workbench.tabs.aria': 'Giao diện bàn làm việc điều phối tác vụ',
    'orchestration.workbench.tabs.queue': 'Hàng chờ {count}',
    'orchestration.workbench.tabs.runs': 'Lịch sử chạy {count}',
    'orchestration.workbench.tabs.detail': 'Chi tiết chạy',
    'orchestration.queue.empty.title': 'Hiện không có tác vụ xếp hàng',
    'orchestration.queue.empty.subtitle': 'Tác vụ hàng loạt có thể xếp hàng trước, rồi khởi động hàng chờ.',
    'orchestration.runs.empty.title': 'Chưa có lịch sử chạy',
    'orchestration.runs.empty.subtitle': 'Lịch sử chạy gần đây sẽ hiển thị sau khi thực thi.',
    'orchestration.detail.refresh': 'Làm mới chi tiết',
    'orchestration.detail.retry': 'Thử lại',
    'orchestration.detail.retrying': 'Đang thử lại...',
    'orchestration.detail.empty.title': 'Chọn một lịch sử chạy để xem chi tiết',
    'orchestration.detail.empty.subtitle': 'Trạng thái nút, tóm tắt và log sẽ hiển thị ở đây.',
    'orchestration.detail.summary.status': 'Trạng thái',
    'orchestration.detail.summary.duration': 'Thời gian',
    'orchestration.detail.summary.nodes': 'Số nút',
    'orchestration.detail.summary.summary': 'Tóm tắt',
    'orchestration.detail.node.meta': '{id} · thử {attempts} lần · tự sửa {autoFix}',

    // Skills
    'skills.localLabel': '{target} / Skills cục bộ',
    'skills.counts': 'Đã cài {installed} · Có thể nhập {importable}',

    // Status
    'status.currentSource': 'Nguồn hiện tại',
    'status.sessionCount': 'Số phiên',
    'status.range': 'Phạm vi thống kê',
    'status.totalSessions': 'Tổng phiên',
    'status.totalMessages': 'Tổng tin nhắn',
    'status.engine': 'Động cơ',
    'status.concurrency': 'Độ đồng thời',
    'status.running': 'Đang chạy',
    'status.queued': 'Đang xếp hàng',
    'status.runs': 'Lịch sử chạy',
    'status.currentTarget': 'Mục tiêu hiện tại',
    'status.localSkills': 'Skills cục bộ',
    'status.importable': 'Có thể nhập',
    'status.importableDirect': 'Có thể nhập trực tiếp',
    'status.pm': 'Trình quản lý gói',
    'status.action': 'Thao tác hiện tại',
    'status.registry': 'Registry',
    'status.claudeConfig': 'Cấu hình Claude',
    'status.claudeModel': 'Mô hình Claude',
    'status.openclawConfig': 'Cấu hình OpenClaw',
    'status.workspaceFile': 'Tệp không gian làm việc',
    'status.configMode': 'Chế độ cấu hình',
    'status.currentProvider': 'Provider hiện tại',
    'status.currentModel': 'Mô hình hiện tại',
    'status.quickSwitchProvider': 'Chuyển đổi nhanh Provider',

    // Settings
    'settings.tab.general': 'Chung',
    'settings.tab.data': 'Dữ liệu',
    'settings.tabs.aria': 'Danh mục cài đặt',
    'settings.quickSettings.title': 'Cài đặt nhanh',
    'settings.sharePrefix.title': 'Tiền tố lệnh chia sẻ',
    'settings.sharePrefix.meta': 'Ảnh hưởng đến tiền tố "Sao chép lệnh chia sẻ" trong Web UI',
    'settings.sharePrefix.label': 'Tiền tố',
    'settings.sharePrefix.hint': 'Mặc định dùng npm start trong dự án, cũng có thể chuyển sang codexmate toàn cục. Cài đặt này được lưu cache cục bộ trên trình duyệt.',
    'settings.backup.title': 'Sao lưu dữ liệu',
    'settings.backup.meta': 'Xuất / Nhập cấu hình Claude và Codex',
    'settings.claude.title': 'Cấu hình Claude',
    'settings.claude.meta': 'Sao lưu / Nhập ~/.claude',
    'settings.codex.title': 'Cấu hình Codex',
    'settings.codex.meta': 'Sao lưu / Nhập ~/.codex',
    'settings.backup.progress': 'Đang sao lưu {percent}%',
    'settings.backup.oneClickClaude': 'Sao lưu nhanh ~/.claude',
    'settings.backup.importClaude': 'Nhập bản sao lưu ~/.claude',
    'settings.backup.oneClickCodex': 'Sao lưu nhanh ~/.codex',
    'settings.backup.importCodex': 'Nhập bản sao lưu ~/.codex',
    'settings.importing': 'Đang nhập...',
    'settings.trashConfig.title': 'Cấu hình thùng rác',
    'settings.trashConfig.meta': 'Bật/tắt thùng rác và số ngày tự động dọn dẹp',
    'settings.deleteBehavior.title': 'Hành vi xóa phiên',
    'settings.deleteBehavior.meta': 'Quyết định xem "Xóa" có vào thùng rác trước không',
    'settings.deleteBehavior.toggle': 'Chuyển phiên vào thùng rác trước khi xóa',
    'settings.deleteBehavior.hint': 'Mặc định bật. Khi tắt, xóa trong trình duyệt phiên sẽ xóa vĩnh viễn ngay, không vào thùng rác.',
    'settings.trash.title': 'Thùng rác',
    'settings.trash.meta': 'Phiên đã xóa (có thể khôi phục/xóa hẳn)',
    'settings.trash.refresh': 'Làm mới danh sách',
    'settings.trash.refreshing': 'Đang làm mới...',
    'settings.trash.clear': 'Dọn sạch thùng rác',
    'settings.trash.clearing': 'Đang dọn...',
    'settings.trash.loading': 'Đang tải thùng rác...',
    'settings.trash.retry': 'Tải danh sách thùng rác thất bại, hãy làm mới lại',
    'settings.trash.restore': 'Khôi phục',
    'settings.trash.restoring': 'Đang khôi phục...',
    'settings.trash.purge': 'Xóa hẳn',
    'settings.trash.purging': 'Đang xóa...',
    'settings.trash.workspace': 'Không gian làm việc',
    'settings.trash.originalFile': 'Tệp gốc',
    'settings.trash.loadMore': 'Tải thêm (còn {count} mục)',
    'settings.trash.retention': 'Tự động dọn dẹp',
    'settings.trash.retentionMeta': 'Bản ghi thùng rác quá số ngày giữ lại sẽ tự động xóa',
    'settings.trash.retentionLabel': 'Số ngày giữ lại',
    'settings.trash.retentionHint': 'Phạm vi 1-365 ngày, mặc định 30 ngày. Tự động dọn bản ghi hết hạn mỗi lần tải thùng rác.',
    'settings.templateConfirm.title': 'Xác nhận hai lần cho mẫu cấu hình',
    'settings.templateConfirm.meta': 'Giảm nguy cơ ghi nhầm',
    'settings.templateConfirm.toggle': 'Xem trước thay đổi trước khi áp dụng mẫu (hai bước: xác nhận → áp dụng)',
    'settings.templateConfirm.hint': 'Khi bật: hiển thị xem trước thay đổi trước, rồi xác nhận ghi.',
    'settings.reset.title': 'Đặt lại cấu hình',
    'settings.reset.meta': 'Thao tác cẩn thận',
    'settings.reset.hint': 'Sẽ sao lưu config.toml trước, rồi ghi cấu hình mặc định.',
    'settings.reset.button': 'Cài lại cấu hình',
    'settings.reset.loading': 'Đang cài lại...',

    // Market/Skills overview
    'market.title': 'Tổng quan Skills',
    'market.subtitle': 'Chuyển đổi mục tiêu và xem Skills cục bộ.',
    'market.refresh': 'Làm mới tổng quan',
    'market.refreshing': 'Đang làm mới...',
    'market.openManager': 'Mở Quản lý Skills',
    'market.target.aria': 'Chọn mục tiêu cài đặt Skills',
    'market.summary.target': 'Mục tiêu cài đặt',
    'market.summary.total': 'Tổng cục bộ',
    'market.summary.configured': 'Có SKILL.md',
    'market.summary.missing': 'Thiếu SKILL.md',
    'market.summary.importable': 'Có thể nhập',
    'market.summary.importableDirect': 'Có thể nhập trực tiếp',
    'market.root.fallback': 'Thư mục mặc định',
    'market.installed.title': 'Skills đã cài',
    'market.installed.note': 'Chỉ hiển thị 6 mục đầu.',
    'market.local.refresh': 'Làm mới cục bộ',
    'market.local.refreshing': 'Đang làm mới...',
    'market.local.loading': 'Đang tải Skills cục bộ...',
    'market.local.empty': 'Hiện chưa có skill nào được cài đặt.',
    'market.pill.verified': 'Đã xác minh',
    'market.pill.missingSkill': 'Cần bổ sung SKILL.md',
    'market.import.title': 'Nguồn có thể nhập',
    'market.import.note': 'Quét và nhập vào {target} hiện tại.',
    'market.import.scan': 'Quét nguồn',
    'market.import.scanning': 'Đang quét...',
    'market.import.loading': 'Đang quét skill có thể nhập...',
    'market.import.empty': 'Chưa quét được skill nào có thể nhập.',
    'market.pill.importableDirect': 'Có thể nhập trực tiếp',
    'market.pill.importMissing': 'Thiếu SKILL.md',
    'market.actions.title': 'Điểm vào phân phối',
    'market.actions.note': 'Tất cả thao tác áp dụng cho mục tiêu cài đặt hiện tại.',
    'market.action.manage.title': 'Quản lý Skills cục bộ',
    'market.action.manage.copy': 'Quản lý skills đã cài trong {target} hiện tại',
    'market.action.crossImport.title': 'Nhập liên ứng dụng',
    'market.action.crossImport.copy': 'Nhập vào {target} hiện tại',
    'market.action.zipImport.title': 'Nhập ZIP',
    'market.action.zipImport.copy': 'Nhập từ ZIP vào mục tiêu hiện tại',
    'market.help.title': 'Hướng dẫn thao tác',
    'market.help.target.title': 'Chuyển đổi mục tiêu',
    'market.help.target.copy': 'Thao tác hiện tại ghi vào thư mục {target}.',
    'market.help.crossImport.title': 'Nhập liên ứng dụng',
    'market.help.crossImport.copy': 'Nhập skill chưa được quản lý từ máy chủ khác.',
    'market.help.zipImport.title': 'Nhập ZIP',
    'market.help.zipImport.copy': 'Nhập skill cục bộ từ ZIP.',

    // Claude config
    'claude.addProvider': 'Thêm nhà cung cấp',
    'claude.applyDefault': 'Mặc định áp dụng vào ~/.claude/settings.json.',
    'claude.presetProviders': 'Nhà cung cấp đặt sẵn',
    'claude.customConfig': 'Cấu hình tùy chỉnh',
    'claude.model': 'Mô hình',
    'claude.model.placeholder': 'Ví dụ: claude-3-7-sonnet',
    'claude.model.hint': 'Sau khi sửa mô hình sẽ tự động lưu và áp dụng vào cấu hình hiện tại.',
    'claude.health.title': 'Kiểm tra sức khỏe cấu hình',
    'claude.health.run': 'Chạy kiểm tra',
    'claude.health.running': 'Đang kiểm tra...',
    'claude.health.hint': 'Sẽ kiểm tra khả dụng của tất cả cấu hình Claude hàng loạt và làm mới hiển thị độ trễ.',
    'claude.health.progress': 'Đã xong {done}/{total} · Thất bại {failed}',
    'claude.md.title': 'CLAUDE.md',
    'claude.md.open': 'Mở CLAUDE.md',
    'claude.md.hint': 'Đọc ghi ~/.claude/CLAUDE.md.',
    'claude.model.unset': 'Chưa đặt mô hình',
    'claude.configured': 'Đã cấu hình',
    'claude.notConfigured': 'Chưa cấu hình',
    'claude.action.edit': 'Chỉnh sửa',
    'claude.action.delete': 'Xóa',
    'claude.action.shareDisabled': 'Chia sẻ lệnh nhập',
    'claude.action.editAria': 'Chỉnh sửa cấu hình Claude: {name}',
    'claude.action.deleteAria': 'Xóa cấu hình Claude: {name}',
    'claude.action.clone': 'Nhân bản',
    'claude.action.cloneAria': 'Nhân bản cấu hình Claude: {name}',
    'claude.localBridge.poolTitle': 'Nhóm luân phiên',
    'claude.localBridge.poolHint': 'Tick để tham gia cân bằng tải',
    'claude.localBridge.noProviders': 'Chưa có nhà cung cấp khả dụng, hãy thêm nhà cung cấp kết nối trực tiếp trước',
    'claude.localBridge.disabled': 'Chưa bật',
    'claude.localBridge.enabled': 'Đã bật',

    // OpenClaw
    'openclaw.applyHint': 'Ghi vào ~/.openclaw/openclaw.json, hỗ trợ JSON5.',
    'openclaw.workspace.title': 'Không gian làm việc OpenClaw',
    'openclaw.configs.hint': 'Chọn cấu hình thường dùng, hoặc vào trình soạn thảo để duy trì JSON5 đầy đủ.',
    'openclaw.agents.hint': 'Đọc ghi AGENTS.md của Workspace, đường dẫn mặc định ~/.openclaw/workspace/AGENTS.md.',
    'openclaw.agents.open': 'Mở AGENTS.md',
    'openclaw.workspaceFile': 'Tệp không gian làm việc',
    'openclaw.workspace.placeholder': 'Ví dụ: SOUL.md',
    'openclaw.workspace.hint': 'Chỉ tệp .md trong Workspace.',
    'openclaw.workspace.open': 'Mở tệp không gian làm việc',
    'openclaw.configured': 'Đã cấu hình',
    'openclaw.notConfigured': 'Chưa cấu hình',
    'openclaw.action.edit': 'Chỉnh sửa',
    'openclaw.action.delete': 'Xóa',
    'openclaw.action.applyAria': 'Áp dụng cấu hình OpenClaw: {name}',
    'openclaw.action.editAria': 'Chỉnh sửa cấu hình OpenClaw: {name}',
    'openclaw.action.deleteAria': 'Xóa cấu hình OpenClaw: {name}',
});

export { vi };
