'use strict';

const SAFE_EXTERNAL_PROTOCOLS = new Set(['http:', 'https:']);

function parsedUrl(value) {
  try {
    return new URL(value);
  } catch {
    return null;
  }
}

function isTrustedUrl(value, trustedOrigin) {
  const candidate = parsedUrl(value);
  const trusted = parsedUrl(trustedOrigin);
  return Boolean(candidate && trusted && candidate.origin === trusted.origin);
}

function isSafeExternalUrl(value) {
  const candidate = parsedUrl(value);
  return Boolean(candidate && SAFE_EXTERNAL_PROTOCOLS.has(candidate.protocol));
}

function isTrustedIpcSender(event, trustedOrigin) {
  return isTrustedUrl(event?.senderFrame?.url, trustedOrigin);
}

// Renderer-selectable session kinds — a closed, fixed enum. The renderer
// requests a KIND of session; it never supplies a program or argv. Electron
// main (main.js) is the only place that maps a sessionType to an actual
// executable + args, so a compromised or malicious renderer can never smuggle
// an arbitrary command into the pty bridge through this option object.
const PTY_SESSION_TYPES = new Set(['user-shell', 'yana-chat']);
const PTY_SESSION_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function normalizeDims(value = {}) {
  const cols = value.cols ?? 80;
  const rows = value.rows ?? 24;
  if (!Number.isInteger(cols) || cols < 20 || cols > 500) {
    throw new TypeError('terminal cols must be an integer between 20 and 500');
  }
  if (!Number.isInteger(rows) || rows < 5 || rows > 300) {
    throw new TypeError('terminal rows must be an integer between 5 and 300');
  }
  return { cols, rows };
}

function normalizePtyStartOptions(value = {}) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new TypeError('terminal options must be an object');
  }

  const { cols, rows } = normalizeDims(value);

  const sessionType = value.sessionType ?? 'user-shell';
  if (typeof sessionType !== 'string' || !PTY_SESSION_TYPES.has(sessionType)) {
    throw new TypeError(`terminal sessionType must be one of: ${[...PTY_SESSION_TYPES].join(', ')}`);
  }

  return { cols, rows, sessionType };
}

function normalizePtyResizeOptions(value = {}) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new TypeError('terminal resize options must be an object');
  }
  return normalizeDims(value);
}

function normalizePtySessionId(value) {
  if (typeof value !== 'string' || !PTY_SESSION_ID.test(value)) {
    throw new TypeError('terminal session id must be a UUID generated by Yana Desktop');
  }
  return value;
}

function normalizePtyInput(value) {
  if (typeof value !== 'string') throw new TypeError('terminal input must be a string');
  if (value.length > 1_048_576 || value.includes('\0')) {
    throw new TypeError('terminal input must be NUL-free and at most 1 MiB');
  }
  return value;
}

module.exports = {
  isSafeExternalUrl,
  isTrustedIpcSender,
  isTrustedUrl,
  normalizePtyInput,
  normalizePtyResizeOptions,
  normalizePtySessionId,
  normalizePtyStartOptions,
  PTY_SESSION_TYPES,
};
