#!/usr/bin/env bash
# Yana AI v1.3.31 — Skill Trigger Phrase Test
#
# Verifies that skill SKILL.md description fields contain the right trigger phrases.
# This does NOT test AI routing — it tests that the descriptions are correctly written
# so they would route correctly when read by an agent.
#
# Usage: bash core/tests/skills/test-skill-triggering.sh

set -uo pipefail

SKILLS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/skills"
PASS=0
FAIL=0

check_skill() {
    local skill_name="$1"
    local expected_phrase="$2"
    local skill_file="$SKILLS_DIR/$skill_name/SKILL.md"

    if [[ ! -f "$skill_file" ]]; then
        echo "FAIL [$skill_name]: SKILL.md not found at $skill_file"
        FAIL=$((FAIL + 1))
        return
    fi

    if grep -qi "$expected_phrase" "$skill_file" 2>/dev/null; then
        echo "PASS [$skill_name]: found trigger phrase '$expected_phrase'"
        PASS=$((PASS + 1))
    else
        echo "FAIL [$skill_name]: trigger phrase '$expected_phrase' NOT found in description"
        FAIL=$((FAIL + 1))
    fi
}

echo "=== Yana AI Skill Trigger Phrase Test ==="
echo "Skills dir: $SKILLS_DIR"
echo ""

# Core existing skills
check_skill "git-lessons"        "past bugs"
check_skill "gitnexus-guide" "codebase"

# New skills from v1.3.12 Superpowers import + v1.3.13 glebis/claude-skills
check_skill "plan-first"         "implement"
check_skill "plan-first"         "multi-step"
check_skill "verify-before-done" "done"
check_skill "verify-before-done" "fixed"
check_skill "debug-protocol"     "bug"
check_skill "debug-protocol"     "error"
check_skill "branch-finish"      "merge"
check_skill "branch-finish"      "done"
check_skill "worktree-safety"    "experiment"
check_skill "worktree-safety"    "feature"
check_skill "tdd"                "red green refactor"
check_skill "tdd"                "test-driven"

# New skills from v1.3.15
check_skill "executing-plans"         "execute"
check_skill "executing-plans"         "proceed"
check_skill "requesting-code-review"  "review this"
check_skill "requesting-code-review"  "code review"
check_skill "receiving-code-review"   "review comments"
check_skill "receiving-code-review"   "address the feedback"
check_skill "writing-skills"          "create a skill"
check_skill "writing-skills"          "write a skill"

# LSP navigation skill (v1.3.16)
check_skill "lsp-navigation"     "defined"
check_skill "lsp-navigation"     "references"
check_skill "lsp-navigation"     "grep"

# Telemetry analysis skill (v1.3.20)
check_skill "telemetry-analysis" "hook"
check_skill "telemetry-analysis" "audit"
check_skill "telemetry-analysis" "telemetry"

# Subagent dependency skill (v1.3.20)
check_skill "subagent-dependency" "parallel"
check_skill "subagent-dependency" "orchestrate"
check_skill "subagent-dependency" "dependency"

# alirezarezvani/claude-skills imports (v1.3.22)
check_skill "agenthub"           "parallel"
check_skill "agenthub"           "worktree"
check_skill "write-a-skill"      "skill"
check_skill "handoff"            "handoff"
check_skill "caveman"            "caveman"
check_skill "code-tour"          "tour"
check_skill "chaos-engineering"  "chaos"
check_skill "llm-cost-optimizer" "cost"
check_skill "pulse"              "reddit"
check_skill "research"           "research"

# disler-inspired skills (v1.3.22)
check_skill "session-context"    "git"
check_skill "pre-compact-backup" "compact"

# sangrokjung/claude-forge skills (v1.3.24)
check_skill "team-orchestrator"      "orchestrat"
check_skill "strategic-compact"      "compact"
check_skill "session-wrap"           "session"
check_skill "verification-engine"    "verification"
check_skill "skill-factory"          "skill"
check_skill "security-compliance"    "compliance"
check_skill "security-pipeline"      "security"
check_skill "stride-analysis-patterns" "threat"
check_skill "debugging-strategies"   "debug"
check_skill "extract-errors"         "error"
check_skill "build-system"           "build"
check_skill "cache-components"       "cache"
check_skill "verify-implementation"  "verify"

# karanb192-inspired skills (v1.3.24)
check_skill "hook-block-commands"    "block"
check_skill "hook-protect-secrets"   "secret"

# qdhenry/Claude-Command-Suite imports (v1.3.17)
check_skill "audit-env-variables"    "env"
check_skill "audit-env-variables"    "security"
check_skill "remove-dead-code"       "dead code"
check_skill "remove-dead-code"       "unused"
check_skill "file-watcher"           "file change"
check_skill "file-watcher"           "chokidar"
check_skill "setup-agent-tail"       "agent-tail"
check_skill "setup-agent-tail"       "log"

# rohitg00/affaan-m imports (v1.3.18) — phase 6
check_skill "api-design"             "REST"
check_skill "api-design"             "pagination"
check_skill "backend-patterns"       "backend"
check_skill "backend-patterns"       "Node.js"
check_skill "coding-standards"       "naming"
check_skill "coding-standards"       "readability"
check_skill "deep-research"          "research"
check_skill "deep-research"          "firecrawl"
check_skill "documentation-lookup"   "Context7"
check_skill "documentation-lookup"   "framework"
check_skill "e2e-testing"            "Playwright"
check_skill "e2e-testing"            "E2E"
check_skill "security-review"        "authentication"
check_skill "security-review"        "security"
check_skill "tdd-workflow"           "test-driven"
check_skill "tdd-workflow"           "coverage"
check_skill "verification-loop"      "verification"
check_skill "agent-introspection-debugging" "debugging"
check_skill "agent-introspection-debugging" "introspection"
check_skill "frontend-patterns"      "React"
check_skill "frontend-patterns"      "frontend"
check_skill "mcp-server-patterns"    "MCP"
check_skill "mcp-server-patterns"    "tools"

# gitnexus skills beyond gitnexus-guide (v1.3.11)
check_skill "gitnexus-cli"            "analyze"
check_skill "gitnexus-cli"            "index"
check_skill "gitnexus-debugging"      "bug"
check_skill "gitnexus-debugging"      "error"
check_skill "gitnexus-exploring"      "architecture"
check_skill "gitnexus-exploring"      "how"
check_skill "gitnexus-impact-analysis" "break"
check_skill "gitnexus-impact-analysis" "impact"
check_skill "gitnexus-pr-review"      "pull request"
check_skill "gitnexus-pr-review"      "review"
check_skill "gitnexus-refactoring"    "refactor"
check_skill "gitnexus-refactoring"    "rename"

# karpathy guidelines + l1-promote (v1.3.17 / v1.3.26)
check_skill "karpathy-guidelines"    "overcomplication"
check_skill "karpathy-guidelines"    "LLM"
check_skill "l1-promote"             "L2"
check_skill "l1-promote"             "promote"

# v1.3.27 — security skill pack + design/UX branch
check_skill "red-team-check"         "attack"
check_skill "red-team-check"         "red.team"
check_skill "blue-team-fix"          "vulnerability"
check_skill "blue-team-fix"          "blue.team"
check_skill "purple-team-report"     "purple"
check_skill "design-taste-frontend"  "visual"
check_skill "design-taste-frontend"  "taste"
check_skill "image-to-code"          "screenshot"
check_skill "image-to-code"          "image"
check_skill "ui-redesign"            "redesign"
check_skill "output-enforcement"     "output"
check_skill "minimalist-ui"          "minimalist"

# v1.3.28 — UI expansion
check_skill "aesthetic-anchor"       "visual"
check_skill "aesthetic-anchor"       "aesthetic"
check_skill "accessibility-audit"    "WCAG"
check_skill "accessibility-audit"    "accessibility"
check_skill "design-system-gen"      "design system"
check_skill "design-system-gen"      "token"
check_skill "ux-heuristics"          "heuristic"
check_skill "ux-heuristics"          "Nielsen"

# v1.3.29 — design/performance branch
check_skill "multi-agent-handoff"    "handoff"
check_skill "multi-agent-handoff"    "context"
check_skill "typography-system"      "font"
check_skill "typography-system"      "type"
check_skill "motion-design"          "animation"
check_skill "motion-design"          "easing"
check_skill "ui-states"              "loading"
check_skill "ui-states"              "skeleton"
check_skill "mobile-ux"              "touch"
check_skill "mobile-ux"              "mobile"
check_skill "web-performance"        "Core Web Vitals"
check_skill "web-performance"        "LCP"

# v1.3.30 — AI/LLM + backend/infra branches (83→99)
check_skill "llm-ui-patterns"        "streaming"
check_skill "llm-ui-patterns"        "AI"
check_skill "prompt-engineering"     "chain-of-thought"
check_skill "prompt-engineering"     "prompt"
check_skill "rag-architect"          "RAG"
check_skill "rag-architect"          "retrieval"
check_skill "slo-design"             "SLO"
check_skill "slo-design"             "error budget"
check_skill "incident-response-runbook" "runbook"
check_skill "incident-response-runbook" "incident"
check_skill "i18n-patterns"          "i18n"
check_skill "i18n-patterns"          "RTL"
check_skill "database-patterns"      "schema"
check_skill "database-patterns"      "N+1"
check_skill "auth-patterns"          "JWT"
check_skill "auth-patterns"          "auth"
check_skill "resilience-patterns"    "circuit breaker"
check_skill "resilience-patterns"    "retry"
check_skill "event-driven-architecture" "event"
check_skill "event-driven-architecture" "Kafka"
check_skill "observability-instrumentation" "structured"
check_skill "observability-instrumentation" "trace"
check_skill "cicd-patterns"          "CI/CD"
check_skill "cicd-patterns"          "pipeline"
check_skill "refactor-patterns"      "strangler"
check_skill "refactor-patterns"      "refactor"
check_skill "data-privacy"           "PII"
check_skill "data-privacy"           "privacy"
check_skill "graphql-patterns"       "GraphQL"
check_skill "graphql-patterns"       "N+1"
check_skill "adr-writing"            "ADR"
check_skill "adr-writing"            "decision"

# v1.3.31 — caching-patterns, api-rate-limiting
check_skill "caching-patterns"       "cache"
check_skill "caching-patterns"       "invalidat"
check_skill "api-rate-limiting"      "rate limit"
check_skill "api-rate-limiting"      "429"

# post v1.3.31 skills — error-handling, secret-management
check_skill "error-handling"         "error code"
check_skill "error-handling"         "stack trace"
check_skill "secret-management"      "secret"
check_skill "secret-management"      "rotation"
check_skill "distributed-tracing"    "trace"
check_skill "distributed-tracing"    "OpenTelemetry"
check_skill "contract-testing"       "contract"
check_skill "contract-testing"       "Pact"

# v1.3.31 session — load-testing, feature-flags, websocket-patterns, mlops, cloud-cost-optimization
check_skill "load-testing"           "k6"
check_skill "load-testing"           "load test"
check_skill "feature-flags"          "feature flag"
check_skill "feature-flags"          "LaunchDarkly"
check_skill "websocket-patterns"     "WebSocket"
check_skill "websocket-patterns"     "real-time"
check_skill "mlops"                  "model"
check_skill "mlops"                  "drift"
check_skill "cloud-cost-optimization" "cost"
check_skill "cloud-cost-optimization" "rightsizing"

# v1.3.32 — design engineering skill pack (Ibelick, emilkowalski, shadcn-ui, millionco, raphaelsalaja, pbakaus, jakubkrehel)
check_skill "baseline-ui"            "baseline"
check_skill "baseline-ui"            "Tailwind"
check_skill "fixing-accessibility"   "keyboard"
check_skill "fixing-accessibility"   "ARIA"
check_skill "fixing-motion-performance" "compositor"
check_skill "fixing-motion-performance" "layout thrashing"
check_skill "shadcn-patterns"        "shadcn"
check_skill "shadcn-patterns"        "cva"
check_skill "react-doctor"           "re-render"
check_skill "react-doctor"           "stale closure"
check_skill "animation-principles"   "squash"
check_skill "animation-principles"   "anticipation"
check_skill "impeccable"             "generic"
check_skill "impeccable"             "hover"
check_skill "interface-feel"         "micro-interaction"
check_skill "interface-feel"         "spring"
check_skill "design-engineering"     "design engineer"
check_skill "design-engineering"     "handoff"

# v1.3.32 — IaC / DevOps pack
check_skill "kubernetes-patterns"    "Kubernetes"
check_skill "kubernetes-patterns"    "CrashLoopBackOff"
check_skill "terraform-patterns"     "Terraform"
check_skill "terraform-patterns"     "remote state"
check_skill "docker-patterns"        "Dockerfile"
check_skill "docker-patterns"        "multi-stage"
check_skill "serverless-patterns"    "Lambda"
check_skill "serverless-patterns"    "cold start"

# v1.3.32 — TypeScript, Next.js, State, Testing, Monorepo, DB Migrations pack
check_skill "typescript-patterns"    "branded"
check_skill "typescript-patterns"    "discriminated union"
check_skill "nextjs-patterns"        "App Router"
check_skill "nextjs-patterns"        "server action"
check_skill "state-management-patterns" "Zustand"
check_skill "state-management-patterns" "TanStack"
check_skill "unit-testing-patterns"  "Arrange"
check_skill "unit-testing-patterns"  "Vitest"
check_skill "monorepo-patterns"      "Turborepo"
check_skill "monorepo-patterns"      "workspace"
check_skill "database-migrations"    "expand-contract"
check_skill "database-migrations"    "zero-downtime"

# v1.3.32 — agent orchestration + security + AI team (3 sources: gnap/hcom, VoltAgent/Trail of Bits, Hivemoot)
check_skill "git-native-agent-protocol"  "GNAP"
check_skill "git-native-agent-protocol"  "task queue"
check_skill "agent-messaging-patterns"   "signal"
check_skill "agent-messaging-patterns"   "approval"
check_skill "adversarial-prompt-testing" "prompt injection"
check_skill "adversarial-prompt-testing" "jailbreak"
check_skill "supply-chain-security"      "SBOM"
check_skill "supply-chain-security"      "provenance"
check_skill "zero-trust-patterns"        "mTLS"
check_skill "zero-trust-patterns"        "never trust"
check_skill "agent-safety-patterns"      "capability"
check_skill "agent-safety-patterns"      "sandbox"
check_skill "ai-team-workflow"           "propose"
check_skill "ai-team-workflow"           "vote"

# v1.3.32 — AutoGen + Anthropic caching + Vercel AI SDK
check_skill "auto-feedback-loop"         "self-correcting"
check_skill "auto-feedback-loop"         "AutoGen"
check_skill "prompt-caching-strategy"   "cache_control"
check_skill "prompt-caching-strategy"   "cache breakpoint"
check_skill "generative-ui-patterns"    "useChat"
check_skill "generative-ui-patterns"    "streamText"

# v1.3.32 — Security guardrails + premium backgrounds + patching loop
check_skill "apply-premium-background"   "dot grid"
check_skill "apply-premium-background"   "aurora"
check_skill "apply-premium-background"   "mesh gradient"
check_skill "leak-check"                 "leaked secrets"
check_skill "leak-check"                 "API keys"
check_skill "leak-check"                 "scan for"
check_skill "autonomous-patching-loop"   "self-heal"
check_skill "autonomous-patching-loop"   "scan and fix"
check_skill "autonomous-patching-loop"   "auto-fix"

# v1.3.32 — Codebase ingestion + research team + tree-of-thoughts
check_skill "ingest-repo"               "ingest this repo"
check_skill "ingest-repo"               "map the codebase"
check_skill "ingest-repo"               "dependency graph"
check_skill "research-team"             "autonomous research"
check_skill "research-team"             "research team"
check_skill "research-team"             "investigate"
check_skill "tree-of-thoughts"          "tree of thoughts"
check_skill "tree-of-thoughts"          "plan 3 approaches"
check_skill "tree-of-thoughts"          "self-critique"

# v1.3.33 — Cross-engine + Token ROI
check_skill "token-roi"                 "token usage"
check_skill "token-roi"                 "cost per fix"
check_skill "token-roi"                 "am I wasting tokens"

# v1.3.35 — memory-gc
check_skill "memory-gc"                 "L2"
check_skill "memory-gc"                 "promote"

# v1.3.36 — UI skills (design-tokens, color, typography, motion, layouts)
check_skill "design-tokens-system"      "design token"
check_skill "design-tokens-system"      "style-dictionary"
check_skill "color-math-system"         "OKLAB"
check_skill "color-math-system"         "palette"
check_skill "typography-scale"          "golden ratio"
check_skill "typography-scale"          "CJK"
check_skill "motion-physics"            "spring"
check_skill "motion-physics"            "easing"
check_skill "component-layout-patterns" "dashboard"
check_skill "component-layout-patterns" "masonry"

# v1.3.37 — 100-repo UI skill batch
check_skill "enterprise-design-systems" "B2B"
check_skill "enterprise-design-systems" "design system"
check_skill "advanced-color-math"       "dark.mode"
check_skill "advanced-color-math"       "contrast"
check_skill "advanced-typography"       "fluid type"
check_skill "advanced-typography"       "variable font"
check_skill "advanced-motion-easing"    "spring"
check_skill "advanced-motion-easing"    "GPU"
check_skill "smart-layout-aesthetics"   "virtual"
check_skill "smart-layout-aesthetics"   "floating"

# v1.3.38 — perf & data skills
check_skill "caching-memory-efficiency" "LRU"
check_skill "caching-memory-efficiency" "TTL"
check_skill "high-perf-data-algorithms" "lazy"
check_skill "high-perf-data-algorithms" "stream"
check_skill "profiling-benchmarking"    "benchmark"
check_skill "profiling-benchmarking"    "ops/sec"

# v1.3.39 — db safety, monorepo, LLM validation
check_skill "database-query-safety"     "N+1"
check_skill "database-query-safety"     "SQL injection"
check_skill "monorepo-governance"       "affected"
check_skill "monorepo-governance"       "Turborepo"
check_skill "llm-output-validation"     "hallucination"
check_skill "llm-output-validation"     "structured output"

# v1.3.40 — OWASP LLM + agent attack surface + memory security
check_skill "owasp-llm-top10"           "Prompt Injection"
check_skill "owasp-llm-top10"           "Excessive Agency"
check_skill "agent-attack-surface"      "blast radius"
check_skill "agent-attack-surface"      "MITRE ATLAS"
check_skill "agent-memory-security"     "poisoning"
check_skill "agent-memory-security"     "L1"

# v1.3.43 — state machines, resilience, telemetry
check_skill "state-machine-workflows"   "XState"
check_skill "state-machine-workflows"   "FSM"
check_skill "resilience-circuit-breakers" "circuit breaker"
check_skill "resilience-circuit-breakers" "exponential backoff"
check_skill "agent-telemetry"           "OpenTelemetry"
check_skill "agent-telemetry"           "p95"

# v1.3.44 — vector stores, type-safe RPC, durable queues
check_skill "vector-store-patterns"      "pgvector"
check_skill "vector-store-patterns"      "cosine"
check_skill "type-safe-api-contracts"    "tRPC"
check_skill "type-safe-api-contracts"    "OpenAPI"
check_skill "durable-task-queues"        "BullMQ"
check_skill "durable-task-queues"        "dead-letter"

# v1.3.45 — intercept layer
check_skill "agent-middleware-gate"     "intercept"
check_skill "agent-middleware-gate"     "sanitize"

# v1.3.46 — graph algorithms, AST manipulation, grammar DSL
check_skill "graph-dependency-resolution" "topological"
check_skill "graph-dependency-resolution" "semver"
check_skill "ast-code-manipulation"       "AST"
check_skill "ast-code-manipulation"       "magic-string"
check_skill "grammar-lexer-dsl"           "Chevrotain"
check_skill "grammar-lexer-dsl"           "Handlebars"

# v1.3.47 — sandbox isolation + swarm consensus
check_skill "container-interactivity"    "Docker"
check_skill "container-interactivity"    "nsjail"
check_skill "swarm-consensus"            "veto"
check_skill "swarm-consensus"            "quorum"


# ── v1.5.0: trigger coverage for remaining skills ─────────────────────────────
check_skill "a2a-protocol-patterns"   "Agent-to-Agent"
check_skill "a2a-protocol-patterns"   "protocol"
check_skill "agent-verification-gate"   "Deterministic"
check_skill "agent-verification-gate"   "verification"
check_skill "agentic-failure-modes"   "MASFT"
check_skill "agentic-failure-modes"   "taxonomy"
check_skill "ai-gateway-patterns"   "gateways"
check_skill "ai-gateway-patterns"   "serving"
check_skill "append-only-hypercore"   "Merkle-tree-backed"
check_skill "append-only-hypercore"   "append-only"
check_skill "archive-stream-patterns"   "Streaming"
check_skill "archive-stream-patterns"   "archive"
check_skill "argocd-gitops"   "Argo"
check_skill "argocd-gitops"   "GitOps"
check_skill "assemblyscript-to-wasm"   "AssemblyScript"
check_skill "assemblyscript-to-wasm"   "TypeScript→WebAssembly"
check_skill "ast-codegen-patterns"   "generation"
check_skill "ast-codegen-patterns"   "back"
check_skill "ast-injection-scanner"   "Statically"
check_skill "ast-injection-scanner"   "scan"
check_skill "async-storage-patterns"   "Async"
check_skill "async-storage-patterns"   "key-value"
check_skill "auth-strategy-patterns"   "Pluggable"
check_skill "auth-strategy-patterns"   "authentication"
check_skill "automerge-crdt"   "Automerge"
check_skill "automerge-crdt"   "CRDT"
check_skill "babel-ast-transform"   "Babel"
check_skill "babel-ast-transform"   "plugin"
check_skill "bft-consensus-patterns"   "Byzantine"
check_skill "bft-consensus-patterns"   "Fault"
check_skill "bunyan-syslog-bridge"   "Bridge"
check_skill "bunyan-syslog-bridge"   "Bunyan"
check_skill "cadvisor-container-metrics"   "cAdvisor"
check_skill "cadvisor-container-metrics"   "container"
check_skill "capability-dropping-linux"   "Linux"
check_skill "capability-dropping-linux"   "capability"
check_skill "chrome-devtools-a11y-audit"   "Accessibility"
check_skill "chrome-devtools-a11y-audit"   "debugging"
check_skill "chrome-devtools-browser-automation"   "Automate"
check_skill "chrome-devtools-browser-automation"   "browser"
check_skill "chrome-devtools-extensions"   "Install"
check_skill "chrome-devtools-extensions"   "manage"
check_skill "chrome-devtools-lcp-debug"   "Largest"
check_skill "chrome-devtools-lcp-debug"   "Contentful"
check_skill "chrome-devtools-mcp"   "Chrome"
check_skill "chrome-devtools-mcp"   "DevTools"
check_skill "chrome-devtools-memory-leak"   "JavaScript/Node.js"
check_skill "chrome-devtools-memory-leak"   "memory"
check_skill "chrome-devtools-network-inspector"   "Inspect"
check_skill "chrome-devtools-network-inspector"   "list"
check_skill "chrome-devtools-performance-trace"   "Record"
check_skill "chrome-devtools-performance-trace"   "analyze"
check_skill "chrome-devtools-screencast"   "screenshots"
check_skill "chrome-devtools-screencast"   "record"
check_skill "circuit-breaker-rollback"   "circuit"
check_skill "circuit-breaker-rollback"   "breaker"
check_skill "cli-config-persistence"   "Hierarchical"
check_skill "cli-config-persistence"   "JSON"
check_skill "cni-network-policies"   "Container"
check_skill "cni-network-policies"   "Network"
check_skill "crossplane-control-plane"   "Crossplane"
check_skill "crossplane-control-plane"   "universal"
check_skill "crypto-pki-patterns"   "X.509"
check_skill "crypto-pki-patterns"   "certificate"
check_skill "cyclomatic-complexity"   "Cyclomatic"
check_skill "cyclomatic-complexity"   "complexity"
check_skill "dagre-layout-engine"   "Directed"
check_skill "dagre-layout-engine"   "acyclic"
check_skill "deepspeed-zero-memory"   "DeepSpeed"
check_skill "deepspeed-zero-memory"   "ZeRO"
check_skill "did-credential-lifecycle"   "Verifiable"
check_skill "did-credential-lifecycle"   "credential"
check_skill "did-resolver-patterns"   "Decentralized"
check_skill "did-resolver-patterns"   "Identifier"
check_skill "disaggregated-prefill-decode"   "Disaggregated"
check_skill "disaggregated-prefill-decode"   "prefill/decode"
check_skill "dompurify-xss-prevention"   "DOMPurify"
check_skill "dompurify-xss-prevention"   "sanitization"
check_skill "ebpf-runtime-tracing"   "eBPF-based"
check_skill "ebpf-runtime-tracing"   "runtime"
check_skill "ebpf-syscall-monitoring"   "intercept"
check_skill "ebpf-syscall-monitoring"   "Linux"
check_skill "ecc-key-management"   "Elliptic"
check_skill "ecc-key-management"   "curve"
check_skill "envoy-proxy-patterns"   "Envoy"
check_skill "envoy-proxy-patterns"   "proxy"
check_skill "eslint-rule-engine"   "ESLint"
check_skill "eslint-rule-engine"   "custom"
check_skill "estree-ast-spec"   "ESTree"
check_skill "estree-ast-spec"   "standard"
check_skill "etcd-distributed-config"   "etcd"
check_skill "etcd-distributed-config"   "distributed"
check_skill "eval-driven-agent-dev"   "Eval-driven"
check_skill "eval-driven-agent-dev"   "agent"
check_skill "extism-wasm-plugins"   "Extism"
check_skill "extism-wasm-plugins"   "plugin"
check_skill "fetch-redirect-ssrf-guard"   "SSRF"
check_skill "fetch-redirect-ssrf-guard"   "prevention"
check_skill "filesystem-isolation-chroot"   "Filesystem"
check_skill "filesystem-isolation-chroot"   "isolation"
check_skill "financial-velocity-budgeting"   "token"
check_skill "financial-velocity-budgeting"   "cost"
check_skill "flash-attention-patterns"   "FlashAttention"
check_skill "flash-attention-patterns"   "IO-aware"
check_skill "flow-anchor-connection"   "Visual"
check_skill "flow-anchor-connection"   "flow"
check_skill "gitignore-pattern-matching"   "gitignore-compatible"
check_skill "gitignore-pattern-matching"   "matching"
check_skill "glob-minimatch-patterns"   "Glob"
check_skill "glob-minimatch-patterns"   "matching"
check_skill "graph-data-structure-ops"   "Pure"
check_skill "graph-data-structure-ops"   "graph"
check_skill "grpc-streaming-rpc"   "gRPC"
check_skill "grpc-streaming-rpc"   "bidirectional"
check_skill "helm-chart-packaging"   "Helm"
check_skill "helm-chart-packaging"   "chart"
check_skill "honeypot-deception-patterns"   "active"
check_skill "honeypot-deception-patterns"   "deception"
check_skill "html-xss-filtering"   "Custom-allowlist"
check_skill "html-xss-filtering"   "filtering"
check_skill "htn-evolutionary-planning"   "Hierarchical"
check_skill "htn-evolutionary-planning"   "Task"
check_skill "http-client-auth-patterns"   "HTTP"
check_skill "http-client-auth-patterns"   "client"
check_skill "http-proxy-intercept"   "HTTP/HTTPS"
check_skill "http-proxy-intercept"   "proxy"
check_skill "http-tunnel-patterns"   "HTTP/HTTPS"
check_skill "http-tunnel-patterns"   "tunneling"
check_skill "hyperdrive-distributed-fs"   "Hyperdrive"
check_skill "hyperdrive-distributed-fs"   "distributed"
check_skill "immutable-identity-patterns"   "Immutable"
check_skill "immutable-identity-patterns"   "agent"
check_skill "in-memory-vector-storage"   "In-memory"
check_skill "in-memory-vector-storage"   "vector"
check_skill "ini-config-parsing"   "configuration"
check_skill "ini-config-parsing"   "file"
check_skill "istio-traffic-management"   "Istio"
check_skill "istio-traffic-management"   "service"
check_skill "jaeger-tracing-visualization"   "Jaeger"
check_skill "jaeger-tracing-visualization"   "distributed"
check_skill "jepsen-fault-testing"   "Jepsen-style"
check_skill "jepsen-fault-testing"   "distributed"
check_skill "jest-test-generation"   "Automated"
check_skill "jest-test-generation"   "Jest"
check_skill "jwt-jws-jwe-patterns"   "JWT/JWS/JWE"
check_skill "jwt-jws-jwe-patterns"   "token"
check_skill "jwt-verification-patterns"   "sign/verify"
check_skill "jwt-verification-patterns"   "claim"
check_skill "k8s-client-js"   "Kubernetes"
check_skill "k8s-client-js"   "JavaScript"
check_skill "k8s-crd-controller"   "Kubernetes"
check_skill "k8s-crd-controller"   "Custom"
check_skill "keccak256-hash-patterns"   "Keccak256"
check_skill "keccak256-hash-patterns"   "ethers.js"
check_skill "ktlint-auto-format"   "ktlint"
check_skill "ktlint-auto-format"   "anti-bikeshedding"
check_skill "kv-cache-optimization"   "KV-cache"
check_skill "kv-cache-optimization"   "optimization"
check_skill "linkerd-service-mesh"   "Linkerd2"
check_skill "linkerd-service-mesh"   "lightweight"
check_skill "lint-staged-git-hook"   "lint-staged"
check_skill "lint-staged-git-hook"   "pre-commit"
check_skill "llama-cpp-quantization"   "llama.cpp"
check_skill "llama-cpp-quantization"   "GGUF/GGML"
check_skill "llm-eval-framework"   "evaluation"
check_skill "llm-eval-framework"   "harness"
check_skill "llm-int8-quantization"   "LLM.int8"
check_skill "llm-int8-quantization"   "bitsandbytes"
check_skill "llm-load-testing"   "inference"
check_skill "llm-load-testing"   "load"
check_skill "loki-log-aggregation"   "Grafana"
check_skill "loki-log-aggregation"   "Loki"
check_skill "magic-string-sourcemap"   "Source"
check_skill "magic-string-sourcemap"   "string"
check_skill "matrix-dimensionality-reduction"   "Linear"
check_skill "matrix-dimensionality-reduction"   "algebra"
check_skill "memgpt-virtual-context"   "MemGPT"
check_skill "memgpt-virtual-context"   "virtual"
check_skill "memory-leak-detection"   "Node.js"
check_skill "memory-leak-detection"   "memory"
check_skill "merkle-mountain-ranges"   "append-only"
check_skill "merkle-mountain-ranges"   "cryptographic"
check_skill "merkle-tree-audit"   "Merkle"
check_skill "merkle-tree-audit"   "tree"
check_skill "mermaid-diagram-generation"   "system"
check_skill "mermaid-diagram-generation"   "diagrams"
check_skill "minimal-base-image-patterns"   "sub-10MB"
check_skill "minimal-base-image-patterns"   "base"
check_skill "mlperf-inference-benchmarks"   "MLPerf"
check_skill "mlperf-inference-benchmarks"   "inference"
check_skill "msgpack-binary-encoding"   "MessagePack"
check_skill "msgpack-binary-encoding"   "binary"
check_skill "multi-agent-debate"   "Multi-agent"
check_skill "multi-agent-debate"   "debate"
check_skill "ndarray-vector-math"   "High-performance"
check_skill "ndarray-vector-math"   "N-dimensional"
check_skill "needle-haystack-context"   "Needle-in-a-Haystack"
check_skill "needle-haystack-context"   "context"
check_skill "nlp-normalization-patterns"   "text"
check_skill "nlp-normalization-patterns"   "normalization"
check_skill "onnxruntime-inference"   "ONNX"
check_skill "onnxruntime-inference"   "Runtime"
check_skill "opentelemetry-distributed-tracing"   "OpenTelemetry"
check_skill "opentelemetry-distributed-tracing"   "distributed"
check_skill "opentelemetry-semantic-telemetry"   "Instrument"
check_skill "opentelemetry-semantic-telemetry"   "multi-agent"
check_skill "overlayfs-runtime-isolation"   "Isolate"
check_skill "overlayfs-runtime-isolation"   "agent"
check_skill "p2p-chronicle-log"   "append-only"
check_skill "p2p-chronicle-log"   "action"
check_skill "pouchdb-sync-patterns"   "CouchDB-compatible"
check_skill "pouchdb-sync-patterns"   "bidirectional"
check_skill "process-existence-check"   "Nanosecond-speed"
check_skill "process-existence-check"   "process"
check_skill "process-list-monitoring"   "System"
check_skill "process-list-monitoring"   "process"
check_skill "prometheus-ai-telemetry"   "Prometheus"
check_skill "prometheus-ai-telemetry"   "metrics"
check_skill "prometheus-scraping-rules"   "Prometheus"
check_skill "prometheus-scraping-rules"   "scrape"
check_skill "prompt-firewall-patterns"   "cognitive"
check_skill "prompt-firewall-patterns"   "security"
check_skill "protobuf-serialization"   "Protocol"
check_skill "protobuf-serialization"   "Buffers"
check_skill "protobufjs-dynamic-schema"   "protobuf.js"
check_skill "protobufjs-dynamic-schema"   "dynamic"
check_skill "pyre-type-analysis"   "Facebook"
check_skill "pyre-type-analysis"   "Pyre"
check_skill "raft-consensus-patterns"   "Raft"
check_skill "raft-consensus-patterns"   "distributed"
check_skill "raft-node-js-impl"   "Node.js-native"
check_skill "raft-node-js-impl"   "Raft"
check_skill "ramdisk-tmpfs-patterns"   "RAM-backed"
check_skill "ramdisk-tmpfs-patterns"   "virtual"
check_skill "raw-socket-diagnostics"   "packet"
check_skill "raw-socket-diagnostics"   "analysis"
check_skill "react-agent-loop"   "ReAct"
check_skill "react-agent-loop"   "Reason+Act"
check_skill "readonly-bind-mount-patterns"   "Read-only"
check_skill "readonly-bind-mount-patterns"   "bind"
check_skill "reflect-metadata-injection"   "Runtime"
check_skill "reflect-metadata-injection"   "metadata"
check_skill "reflexion-verbal-rl"   "Reflexion"
check_skill "reflexion-verbal-rl"   "verbal"
check_skill "regex-escape-redos-guard"   "Prevent"
check_skill "regex-escape-redos-guard"   "ReDoS"
check_skill "repl-code-execution"   "REPL-driven"
check_skill "repl-code-execution"   "dynamic"
check_skill "rewoo-plan-execute"   "ReWOO"
check_skill "rewoo-plan-execute"   "decoupled"
check_skill "runtime-metrics-meters"   "Runtime"
check_skill "runtime-metrics-meters"   "operational"
check_skill "runtime-sandbox-runc"   "Low-level"
check_skill "runtime-sandbox-runc"   "container"
check_skill "sanitize-html-cleanup"   "Strict"
check_skill "sanitize-html-cleanup"   "HTML"
check_skill "secrets-vault-patterns"   "Secure"
check_skill "secrets-vault-patterns"   "secrets"
check_skill "self-refine-critic"   "Self-Refine"
check_skill "self-refine-critic"   "iterative"
check_skill "sglang-radix-attention"   "sGLang"
check_skill "sglang-radix-attention"   "RadixAttention"
check_skill "skill-library-voyager"   "Skill"
check_skill "skill-library-voyager"   "library"
check_skill "snowflake-id-generation"   "Twitter"
check_skill "snowflake-id-generation"   "Snowflake-style"
check_skill "sovereign-interceptor-patterns"   "sovereign"
check_skill "sovereign-interceptor-patterns"   "security"
check_skill "sovereign-overlord-gate"   "Sovereign"
check_skill "sovereign-overlord-gate"   "Overlord"
check_skill "stanford-crypto-patterns"   "Side-channel-resistant"
check_skill "stanford-crypto-patterns"   "cryptography"
check_skill "state-persistence-gateway"   "Selective"
check_skill "state-persistence-gateway"   "state"
check_skill "statsd-metrics-streaming"   "Real-time"
check_skill "statsd-metrics-streaming"   "metrics"
check_skill "storage-fallback-patterns"   "Cross-environment"
check_skill "storage-fallback-patterns"   "storage"
check_skill "stream-pipeline-patterns"   "Node.js"
check_skill "stream-pipeline-patterns"   "stream"
check_skill "stream-to-buffer-patterns"   "Safely"
check_skill "stream-to-buffer-patterns"   "collect"
check_skill "streaming-llm-infinite-context"   "StreamingLLM"
check_skill "streaming-llm-infinite-context"   "attention"
check_skill "string-validation-patterns"   "Comprehensive"
check_skill "string-validation-patterns"   "string"
check_skill "swarm-honeynets"   "Deploy"
check_skill "swarm-honeynets"   "full"
check_skill "swc-compiler-transform"   "Speedy"
check_skill "swc-compiler-transform"   "Compiler"
check_skill "symmetric-encryption-patterns"   "AES-256"
check_skill "symmetric-encryption-patterns"   "symmetric"
check_skill "syscall-filtering-seccomp"   "Linux"
check_skill "syscall-filtering-seccomp"   "seccomp"
check_skill "syslog-integration"   "Linux"
check_skill "syslog-integration"   "syslog"
check_skill "system-info-telemetry"   "Hardware"
check_skill "system-info-telemetry"   "telemetry"
check_skill "tgi-streaming-inference"   "HuggingFace"
check_skill "tgi-streaming-inference"   "Text"
check_skill "toml-config-parsing"   "TOML"
check_skill "toml-config-parsing"   "configuration"
check_skill "traefik-ingress-routing"   "Traefik"
check_skill "traefik-ingress-routing"   "cloud-native"
check_skill "triton-inference-server"   "NVIDIA"
check_skill "triton-inference-server"   "Triton"
check_skill "ts-morph-refactor"   "TypeScript"
check_skill "ts-morph-refactor"   "Compiler"
check_skill "twirp-rpc-patterns"   "Twirp"
check_skill "twirp-rpc-patterns"   "lightweight"
check_skill "uid-gid-privilege-drop"   "UID/GID"
check_skill "uid-gid-privilege-drop"   "privilege"
check_skill "unprivileged-sandbox-bubblewrap"   "Rootless"
check_skill "unprivileged-sandbox-bubblewrap"   "sandbox"
check_skill "vector-distance-metrics"   "Vector"
check_skill "vector-distance-metrics"   "similarity"
check_skill "vllm-paged-attention"   "vLLM"
check_skill "vllm-paged-attention"   "PagedAttention"
check_skill "wamp-pubsub-patterns"   "WAMP"
check_skill "wamp-pubsub-patterns"   "Application"
check_skill "wasm-bindgen-js-interop"   "wasm-bindgen"
check_skill "wasm-bindgen-js-interop"   "Rust↔JavaScript"
check_skill "wasmer-wasm-runtime"   "Wasmer"
check_skill "wasmer-wasm-runtime"   "universal"
check_skill "wasmtime-wasi-sandbox"   "Wasmtime"
check_skill "wasmtime-wasi-sandbox"   "WASI"
check_skill "websocket-protocol-codegen"   "Low-level"
check_skill "websocket-protocol-codegen"   "WebSocket"
check_skill "xstate-actor-model"   "XState"
check_skill "xstate-actor-model"   "finite"
check_skill "yaml-safe-parsing"   "Safe"
check_skill "yaml-safe-parsing"   "YAML"
check_skill "yjs-crdt-sync"   "CRDT"
check_skill "yjs-crdt-sync"   "shared"
check_skill "zero-trust-network-mesh"   "Zero"
check_skill "zero-trust-network-mesh"   "Trust"
check_skill "zip-memory-operations"   "In-memory"
check_skill "zip-memory-operations"   "read/write"
check_skill "zk-proof-patterns"   "Zero-Knowledge"
check_skill "zk-proof-patterns"   "Proof"
check_skill "zlib-stream-compression"   "Node.js"
check_skill "zlib-stream-compression"   "zlib"
check_skill "zombie-process-cleanup"   "reaping"
check_skill "zombie-process-cleanup"   "zombie/orphan"

echo ""
echo "=== Summary ==="
echo "Passed: $PASS"
echo "Failed: $FAIL"
echo "Total:  $((PASS + FAIL))"

if [[ $FAIL -gt 0 ]]; then
    echo "Result: FAIL"
    exit 1
else
    echo "Result: PASS"
    exit 0
fi
