use crate::graph::types::*;
use anyhow::Result;

pub fn cmd_show(data: &GraphData) {
    print!("{}", render_show(data));
}

/// The first `n` bytes of a timestamp, or all of it when it is shorter (or
/// `n` is not a character boundary), so an old or hand-edited graph file
/// cannot make a report panic.
fn date_prefix(stamp: &str, n: usize) -> &str {
    stamp.get(..n).unwrap_or(stamp)
}

fn line(out: &mut String, text: impl AsRef<str>) {
    out.push_str(text.as_ref());
    out.push('\n');
}

fn render_show(data: &GraphData) -> String {
    let mut out = String::new();
    let m = &data.meta;
    let layers = count_layers(&data.nodes);
    let file_nodes = data.nodes.iter().filter(|n| n.node_type == "file").count();
    let func_nodes = data.nodes.iter().filter(|n| n.node_type == "function").count();
    let class_nodes = data.nodes.iter().filter(|n| n.node_type == "class").count();

    line(&mut out, format!("\n  {}", m.project));
    line(&mut out, "");
    line(&mut out, format!("  Languages   {}", m.languages.join(", ")));
    if !m.frameworks.is_empty() {
        line(&mut out, format!("  Frameworks  {}", m.frameworks.join(", ")));
    }
    line(&mut out, format!("  Files       {}", file_nodes));
    if func_nodes > 0  { line(&mut out, format!("  Functions   {}", func_nodes)); }
    if class_nodes > 0 { line(&mut out, format!("  Classes     {}", class_nodes)); }
    line(&mut out, format!("  Edges       {}", data.edges.len()));
    line(&mut out, format!("  Analysed    {}", date_prefix(&m.analysed_at, 19)));
    line(&mut out, "");
    line(&mut out, "  Architecture");
    let mut layer_list: Vec<_> = layers.iter().collect();
    layer_list.sort_by(|a, b| b.1.cmp(a.1));
    for (layer, count) in &layer_list {
        line(&mut out, format!("    {:<24} {} nodes", layer, count));
    }
    line(&mut out, "");
    line(&mut out, format!("  Tour ({} steps)", data.tour.len()));
    for step in data.tour.iter().take(5) {
        line(&mut out, format!("    {:>3}. {}", step.order, step.name));
    }
    if data.tour.len() > 5 {
        line(&mut out, format!("    … and {} more (run `yana-rt graph onboard`)", data.tour.len() - 5));
    }
    line(&mut out, "");
    out
}

pub fn cmd_search(data: &GraphData, query: &str, expand: bool, limit: usize) {
    print!("{}", render_search(data, query, expand, limit));
}

fn render_search(data: &GraphData, query: &str, expand: bool, limit: usize) -> String {
    let mut out = String::new();
    let q = query.to_lowercase();
    let mut hits: Vec<&Node> = data.nodes.iter().filter(|n| {
        n.name.to_lowercase().contains(&q)
            || n.file_path.to_lowercase().contains(&q)
            || n.tags.iter().any(|t| t.to_lowercase().contains(&q))
            || n.language.to_lowercase().contains(&q)
    }).collect();

    hits.sort_by_key(|n| {
        if n.name.to_lowercase() == q { 0 }
        else if n.name.to_lowercase().starts_with(&q) { 1 }
        else { 2 }
    });
    hits.truncate(limit);

    if hits.is_empty() {
        line(&mut out, format!("(no results for '{}')", query));
        return out;
    }
    line(&mut out, format!("\n  Search: {}", query));
    line(&mut out, format!("  {} result(s)\n", hits.len()));
    for n in &hits {
        line(&mut out, format!("  [{:<14}] {}", n.node_type, n.name));
        line(&mut out, format!("               {}", n.file_path));
        if !n.summary.is_empty() {
            line(&mut out, format!("               {}", n.summary.chars().take(80).collect::<String>()));
        }
    }

    if expand && !hits.is_empty() {
        let first_id = &hits[0].id;
        let connected: Vec<&Node> = data.edges.iter()
            .filter(|e| &e.source == first_id || &e.target == first_id)
            .flat_map(|e| {
                let id = if &e.source == first_id { &e.target } else { &e.source };
                data.nodes.iter().find(|n| &n.id == id)
            })
            .take(5)
            .collect();

        if !connected.is_empty() {
            line(&mut out, format!("\n  Connected to '{}':", hits[0].name));
            for n in connected {
                line(&mut out, format!("    → {} ({})", n.name, n.file_path));
            }
        }
    }
    line(&mut out, "");
    out
}

pub fn cmd_onboard(data: &GraphData, out_file: Option<&str>) -> Result<()> {
    let md = render_onboard(data);
    if let Some(path) = out_file {
        std::fs::write(path, &md)?;
        println!("[graph] onboarding guide → {}", path);
    } else {
        print!("{}", md);
    }
    Ok(())
}

fn render_onboard(data: &GraphData) -> String {
    let mut md = String::new();
    md.push_str(&format!("# {} — Onboarding Guide\n\n", data.meta.project));
    md.push_str(&format!(
        "> Generated by `yana-rt graph onboard` · {} files · {} edges\n\n",
        data.nodes.iter().filter(|n| n.node_type == "file").count(),
        data.edges.len()
    ));

    md.push_str("## Project Overview\n\n");
    md.push_str(&format!(
        "**Languages:** {}  \n**Frameworks:** {}  \n**Analysed:** {}\n\n",
        data.meta.languages.join(", "),
        if data.meta.frameworks.is_empty() { "-".to_string() } else { data.meta.frameworks.join(", ") },
        date_prefix(&data.meta.analysed_at, 10)
    ));

    let layers = count_layers(&data.nodes);
    md.push_str("## Architecture\n\n");
    let mut lv: Vec<_> = layers.iter().collect();
    lv.sort_by(|a, b| b.1.cmp(a.1));
    for (layer, count) in lv {
        md.push_str(&format!("- **{}**: {} nodes\n", layer, count));
    }

    md.push_str("\n## Guided Tour\n\n");
    md.push_str("Start here to understand the codebase:\n\n");
    for step in &data.tour {
        md.push_str(&format!(
            "### {}. `{}` ({})\n\n- Path: `{}`\n- Layer: {}\n- Reason: {}\n\n",
            step.order, step.name, step.language,
            step.file_path, step.layer, step.reason
        ));
    }

    // Top connected files
    let mut degree: Vec<(&str, usize)> = {
        let mut map: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
        for e in &data.edges {
            *map.entry(e.target.as_str()).or_default() += 1;
            *map.entry(e.source.as_str()).or_default() += 1;
        }
        map.into_iter().collect()
    };
    degree.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(b.0)));

    md.push_str("## Most Connected Files\n\n");
    for (id, deg) in degree.iter().take(10) {
        if let Some(n) = data.nodes.iter().find(|n| n.id == *id) {
            md.push_str(&format!("- `{}` — {} connections\n", n.file_path, deg));
        }
    }

    md
}

pub fn cmd_diff(data: &GraphData, base: &str, target: &str) -> Result<()> {
    use std::process::Command;
    if base.starts_with('-') {
        anyhow::bail!("base must be a revision, not an option: '{base}'");
    }
    let out = Command::new("git")
        .args(["diff", "--name-only", base])
        .current_dir(target)
        .output()?;
    if !out.status.success() {
        anyhow::bail!("git diff failed: {}", String::from_utf8_lossy(&out.stderr));
    }
    let changed: Vec<&str> = std::str::from_utf8(&out.stdout)?
        .lines().collect();

    if changed.is_empty() {
        println!("No changed files vs {}", base);
        return Ok(());
    }
    println!("\n  Changed files (vs {}):\n", base);
    for f in &changed {
        println!("  ✎  {}", f);
    }

    let impacted = impacted_files(data, &changed);

    if !impacted.is_empty() {
        println!("\n  Impact (files that import changed files):\n");
        for f in &impacted {
            println!("  →  {}", f);
        }
    }
    println!();
    Ok(())
}

/// Files that import any of the changed files (the impact of a change).
fn impacted_files<'a>(data: &'a GraphData, changed: &[&str]) -> Vec<&'a str> {
    let changed_ids: Vec<String> = changed.iter().map(|f| format!("file:{}", f)).collect();
    let mut seen = std::collections::HashSet::new();
    data.edges.iter()
        .filter(|e| changed_ids.contains(&e.target))
        .filter_map(|e| data.nodes.iter().find(|n| n.id == e.source))
        .map(|n| n.file_path.as_str())
        .filter(|path| seen.insert(*path))
        .collect()
}

fn count_layers(nodes: &[Node]) -> std::collections::HashMap<String, usize> {
    let mut map: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    for n in nodes {
        let layer = crate::graph::types::layer_from_path(&n.file_path).to_string();
        *map.entry(layer).or_default() += 1;
    }
    map
}

#[cfg(test)]
mod tests;
