const PROVIDERS = Object.freeze([
  {
    id: "anthropic",
    label: "Claude",
    company: "Anthropic",
    kind: "cloud",
    requiresKey: true,
    envVar: "ANTHROPIC_API_KEY",
    defaultModel: "claude-sonnet-4-6",
  },
  {
    id: "openai",
    label: "OpenAI",
    company: "OpenAI",
    kind: "cloud",
    requiresKey: true,
    envVar: "OPENAI_API_KEY",
    defaultModel: "gpt-4o-mini",
  },
  {
    id: "gemini",
    label: "Gemini",
    company: "Google",
    kind: "cloud",
    requiresKey: true,
    envVar: "GEMINI_API_KEY",
    defaultModel: "gemini-2.0-flash",
  },
  {
    id: "groq",
    label: "Groq",
    company: "Groq",
    kind: "cloud",
    requiresKey: true,
    envVar: "GROQ_API_KEY",
    defaultModel: "llama-3.3-70b-versatile",
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    company: "DeepSeek",
    kind: "cloud",
    requiresKey: true,
    envVar: "DEEPSEEK_API_KEY",
    defaultModel: "deepseek-chat",
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    company: "OpenRouter",
    kind: "cloud",
    requiresKey: true,
    envVar: "OPENROUTER_API_KEY",
    defaultModel: "google/gemma-3-27b-it",
  },
  {
    id: "xai",
    label: "xAI",
    company: "xAI",
    kind: "cloud",
    requiresKey: true,
    envVar: "XAI_API_KEY",
    defaultModel: "grok-3-mini",
  },
  {
    id: "novita",
    label: "Novita",
    company: "Novita AI",
    kind: "cloud",
    requiresKey: true,
    envVar: "NOVITA_API_KEY",
    defaultModel: "meta-llama/llama-3.1-70b-instruct",
  },
  {
    id: "nvidia",
    label: "NVIDIA",
    company: "NVIDIA",
    kind: "cloud",
    requiresKey: true,
    envVar: "NVIDIA_API_KEY",
    defaultModel: "nvidia/llama-3.1-nemotron-70b-instruct",
  },
  {
    id: "minimax",
    label: "MiniMax",
    company: "MiniMax",
    kind: "cloud",
    requiresKey: true,
    envVar: "MINIMAX_API_KEY",
    defaultModel: "abab6.5s-chat",
  },
  {
    id: "glm",
    label: "GLM",
    company: "Zhipu AI",
    kind: "cloud",
    requiresKey: true,
    envVar: "GLM_API_KEY",
    defaultModel: "glm-4-flash",
  },
  {
    id: "huggingface",
    label: "Hugging Face",
    company: "Hugging Face",
    kind: "cloud",
    requiresKey: true,
    envVar: "HUGGINGFACE_API_KEY",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct",
  },
  {
    id: "9router",
    label: "9Router",
    company: "Local gateway",
    kind: "local",
    requiresKey: true,
    envVar: "NINE_ROUTER_API_KEY",
    defaultModel: "kr/claude-sonnet-4.5",
    baseUrl: "http://127.0.0.1:20128/v1",
    discoverable: true,
  },
  {
    id: "kimi",
    label: "Kimi",
    company: "Moonshot AI",
    kind: "cloud",
    requiresKey: true,
    envVar: "MOONSHOT_API_KEY",
    defaultModel: "kimi-k3",
  },
  {
    id: "ollama",
    label: "Ollama",
    company: "On-device",
    kind: "local",
    requiresKey: false,
    envVar: "",
    defaultModel: "llama3.2",
    baseUrl: "http://127.0.0.1:11434",
    discoverable: true,
  },
  {
    id: "lmstudio",
    label: "LM Studio",
    company: "On-device",
    kind: "local",
    requiresKey: false,
    envVar: "",
    defaultModel: "local-model",
    baseUrl: "http://127.0.0.1:1234/v1",
    discoverable: true,
  },
  {
    id: "llamacpp",
    label: "llama.cpp",
    company: "On-device",
    kind: "local",
    requiresKey: false,
    envVar: "",
    defaultModel: "local-model",
    baseUrl: "http://127.0.0.1:8080/v1",
    discoverable: true,
  },
  {
    id: "turbofieldfare",
    label: "TurboFieldfare",
    company: "On-device",
    kind: "local",
    requiresKey: false,
    envVar: "",
    defaultModel: "gemma-4-26b-a4b-it",
    baseUrl: "http://127.0.0.1:8091/v1",
    discoverable: true,
  },
  {
    id: "airllm",
    label: "AirLLM",
    company: "On-device",
    kind: "local",
    requiresKey: false,
    envVar: "",
    defaultModel: "meta-llama/Llama-3.2-3B-Instruct",
    baseUrl: "http://127.0.0.1:8100/v1",
    discoverable: true,
  },
]);

const CUSTOM_PROVIDER = Object.freeze({
  id: "custom",
  label: "OpenAI-compatible",
  company: "User endpoint",
  kind: "custom",
  requiresKey: false,
  envVar: "",
  defaultModel: "",
  baseUrl: "",
  discoverable: true,
  canonical: false,
});

function publicCatalog() {
  return [...PROVIDERS, CUSTOM_PROVIDER].map((provider) => ({
    ...provider,
    canonical: provider.canonical !== false,
    models: provider.defaultModel ? [provider.defaultModel] : [],
  }));
}

function providerById(id) {
  const provider = [...PROVIDERS, CUSTOM_PROVIDER].find(
    (entry) => entry.id === id,
  );
  if (!provider) throw new Error("Unsupported provider");
  return provider;
}

module.exports = { PROVIDERS, CUSTOM_PROVIDER, publicCatalog, providerById };
