#!/usr/bin/env bash
# Switch active AI engine adapter
# Usage: bash core/scripts/switch-engine.sh <claude|cursor|copilot|aider>
set -euo pipefail

ENGINE="${1:-}"
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

usage() {
  echo "Usage: $0 <engine>"
  echo ""
  echo "Engines:"
  echo "  claude   — default (no adapter needed, uses .claude/ hooks natively)"
  echo "  cursor   — activates .cursorrules + .cursor/rules/*.mdc"
  echo "  copilot  — activates .github/copilot-instructions.md"
  echo "  aider    — prints aider CLI command with system prompt"
  echo "  gemini   — generates GEMINI.md from adapters/gemini-code.md"
  echo "  status   — show which adapters are currently active"
  exit 1
}

[[ -z "$ENGINE" ]] && usage

case "$ENGINE" in
  claude)
    echo -e "${GREEN}Claude Code (native) — no adapter needed.${NC}"
    echo "Hooks in core/hooks/ are enforced at runtime via .claude/settings.json"
    echo "Run: bash core/tests/hooks/run-hook-tests.sh to verify"
    ;;

  cursor)
    if [[ -f ".cursorrules" ]]; then
      echo -e "${GREEN}✓ .cursorrules present${NC} ($(wc -l < .cursorrules) lines)"
    else
      echo -e "${RED}✗ .cursorrules missing — regenerate:${NC}"
      echo "  bash core/scripts/switch-engine.sh cursor --regen"
    fi
    if [[ -d ".cursor/rules" ]]; then
      echo -e "${GREEN}✓ .cursor/rules/ present${NC} ($(ls .cursor/rules/*.mdc 2>/dev/null | wc -l) rules)"
    fi

    # ── Hard enforcement: inject safe-run proxy rule into Cursor ──────────────
    mkdir -p ".cursor/rules"
    cat > ".cursor/rules/yamtam-hard-enforcement.mdc" << 'CURSOREOF'
---
description: YAMTAM Hard Enforcement — all bash commands must route through safe-run.sh
alwaysApply: true
---

# YAMTAM Security Gate — Cursor Hard Enforcement

**MANDATORY:** Every bash/shell command you generate MUST be prefixed with the safe-run proxy:

```
bash core/scripts/safe-run.sh --engine cursor <your command here>
```

## Examples

❌ FORBIDDEN:
```bash
rm -rf dist/
git push --force
```

✅ REQUIRED:
```bash
bash core/scripts/safe-run.sh --engine cursor rm -rf dist/
bash core/scripts/safe-run.sh --engine cursor git push --force
```

## Why

YAMTAM's L0–L5 gate stack screens every command for destructive patterns, LD_PRELOAD hijacks,
pipe-to-shell exploits, and elevated-risk operations before execution.
Cursor does not have a native hook layer — safe-run.sh is the enforcement proxy.

## Violations

Any command executed without the safe-run proxy is a TIER-2 security violation.
Log: /tmp/yamtam-audit.log
CURSOREOF
    echo -e "${GREEN}✓ Hard enforcement rule written${NC}: .cursor/rules/yamtam-hard-enforcement.mdc"
    echo ""
    echo -e "${CYAN}Cursor picks up these files automatically.${NC}"
    echo "Hard enforcement active — all bash calls must route through safe-run.sh --engine cursor"
    ;;

  copilot)
    INSTRUCTIONS=".github/copilot-instructions.md"
    if [[ -f "$INSTRUCTIONS" ]]; then
      echo -e "${GREEN}✓ $INSTRUCTIONS present${NC} ($(wc -l < "$INSTRUCTIONS") lines)"
    else
      echo -e "${RED}✗ $INSTRUCTIONS missing${NC}"
      exit 1
    fi
    echo ""
    echo -e "${CYAN}GitHub Copilot reads this file automatically in VS Code.${NC}"
    echo "Ensure: GitHub Copilot extension ≥ 1.100 for instructions support."
    ;;

  aider)
    ADAPTER="adapters/aider.md"
    if [[ ! -f "$ADAPTER" ]]; then
      echo -e "${RED}✗ $ADAPTER missing${NC}"
      exit 1
    fi
    echo -e "${GREEN}✓ Aider adapter ready${NC}"

    # ── Hard enforcement: write .aider.conf.yml with safe-run proxy ───────────
    cat > ".aider.conf.yml" << 'AIDEREOF'
# YAMTAM Hard Enforcement — Aider configuration
# Generated by: bash core/scripts/switch-engine.sh aider

# Route all bash commands through YAMTAM safe-run proxy
shell: bash core/scripts/safe-run.sh --engine aider

# Governance system prompt
system_prompt: adapters/aider.md

# Safety defaults
auto_commits: false
dirty_commits: false
auto_lint: false

# Prevent aider from running arbitrary install commands
read_only:
  - core/gates/
  - core/hooks/
  - core/memory/L1/
AIDEREOF
    echo -e "${GREEN}✓ Hard enforcement config written${NC}: .aider.conf.yml"
    echo ""
    echo -e "${CYAN}Run aider with YAMTAM governance:${NC}"
    echo ""
    echo "  aider --model claude-sonnet-4-6"
    echo ""
    echo "All bash commands routed through safe-run.sh --engine aider (Hard mode)"
    ;;

  gemini)
    ADAPTER="adapters/gemini-code.md"
    DEST="GEMINI.md"
    if [[ ! -f "$ADAPTER" ]]; then
      echo -e "${RED}✗ $ADAPTER missing${NC}"
      exit 1
    fi

    # Backup existing GEMINI.md before overwrite
    if [[ -f "$DEST" ]]; then
      BACKUP="${DEST}.bak.$(date +%Y%m%d_%H%M%S)"
      cp "$DEST" "$BACKUP"
      echo -e "${YELLOW}↩ Backup created:${NC} $BACKUP"
    fi

    # Generate GEMINI.md from adapter source (strip comment-only header lines)
    cp "$ADAPTER" "$DEST"
    echo -e "${GREEN}✓ Generated:${NC} $DEST ($(wc -l < "$DEST") lines)"

    # Log via secure-logger.sh if available
    LOGGER="core/scripts/secure-logger.sh"
    if [[ -x "$LOGGER" ]]; then
      bash "$LOGGER" engine_switch "gemini adapter activated — GEMINI.md written" 2>/dev/null || true
    fi

    echo ""
    echo -e "${CYAN}Enforcement tier summary:${NC}"
    echo "  L0  Audit    — every tool call logged (do not skip)"
    echo "  L1  Scope    — no secret/env access without declaration"
    echo "  L2  Commit   — warn on cross-scope commits"
    echo "  L3  Truth    — no unsupported completion claims"
    echo "  L4  Deploy   — requires YAMTAM_DEPLOY_APPROVED=1"
    echo "  L5  Destruct — hard block rm -rf / DROP TABLE / DELETE without WHERE"
    echo ""
    echo "GEMINI.md is read automatically by Gemini Code CLI on startup."
    echo "For shell-level blocking, additionally run:"
    echo "  bash core/scripts/safe-run.sh --engine gemini -- <command>"
    ;;

  status)
    echo "=== YAMTAM Engine Adapter Status ==="
    echo ""
    [[ -f ".cursorrules" ]] \
      && echo -e "  ${GREEN}✓${NC} Cursor    .cursorrules ($(wc -l < .cursorrules) lines)" \
      || echo -e "  ${YELLOW}✗${NC} Cursor    .cursorrules missing"
    [[ -d ".cursor/rules" ]] \
      && echo -e "  ${GREEN}✓${NC} Cursor    .cursor/rules/ ($(ls .cursor/rules/*.mdc 2>/dev/null | wc -l) .mdc files)" \
      || echo -e "  ${YELLOW}✗${NC} Cursor    .cursor/rules/ missing"
    [[ -f ".github/copilot-instructions.md" ]] \
      && echo -e "  ${GREEN}✓${NC} Copilot   .github/copilot-instructions.md" \
      || echo -e "  ${YELLOW}✗${NC} Copilot   .github/copilot-instructions.md missing"
    [[ -f "adapters/aider.md" ]] \
      && echo -e "  ${GREEN}✓${NC} Aider     adapters/aider.md" \
      || echo -e "  ${YELLOW}✗${NC} Aider     adapters/aider.md missing"
    [[ -f "GEMINI.md" ]] \
      && echo -e "  ${GREEN}✓${NC} Gemini    GEMINI.md ($(wc -l < GEMINI.md) lines)" \
      || echo -e "  ${YELLOW}✗${NC} Gemini    GEMINI.md missing"
    echo ""
    echo -e "  ${GREEN}✓${NC} Claude    native (hooks in core/hooks/)"
    ;;

  *)
    echo -e "${RED}Unknown engine: $ENGINE${NC}"
    usage
    ;;
esac
