#!/usr/bin/env bash
# Switch active AI engine adapter
# Usage: bash core/scripts/switch-engine.sh <claude|cursor|copilot|aider>
set -euo pipefail

ENGINE="${1:-}"
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

usage() {
  echo "Usage: $0 <engine>"
  echo ""
  echo "Engines:"
  echo "  claude   — default (no adapter needed, uses .claude/ hooks natively)"
  echo "  cursor   — activates .cursorrules + .cursor/rules/*.mdc"
  echo "  copilot  — activates .github/copilot-instructions.md"
  echo "  aider    — prints aider CLI command with system prompt"
  echo "  gemini   — generates GEMINI.md from adapters/gemini-code.md"
  echo "  qwen      — prints Aider/OpenRouter command template (advisory mode)"
  echo "  deepseek   — prints Aider/DeepSeek command template (advisory mode)"
  echo "  openrouter — prints generic Aider/OpenRouter template (advisory mode)"
  echo "  status     — show which adapters are currently active"
  exit 1
}

[[ -z "$ENGINE" ]] && usage

case "$ENGINE" in
  claude)
    echo -e "${GREEN}Claude Code (native) — no adapter needed.${NC}"
    echo "Hooks in core/hooks/ are enforced at runtime via .claude/settings.json"
    echo "Run: bash core/tests/hooks/run-hook-tests.sh to verify"
    ;;

  cursor)
    if [[ -f ".cursorrules" ]]; then
      echo -e "${GREEN}✓ .cursorrules present${NC} ($(wc -l < .cursorrules) lines)"
    else
      echo -e "${RED}✗ .cursorrules missing — regenerate:${NC}"
      echo "  bash core/scripts/switch-engine.sh cursor --regen"
    fi
    if [[ -d ".cursor/rules" ]]; then
      echo -e "${GREEN}✓ .cursor/rules/ present${NC} ($(ls .cursor/rules/*.mdc 2>/dev/null | wc -l) rules)"
    fi

    # ── Hard enforcement: inject safe-run proxy rule into Cursor ──────────────
    mkdir -p ".cursor/rules"
    cat > ".cursor/rules/yamtam-hard-enforcement.mdc" << 'CURSOREOF'
---
description: YAMTAM Hard Enforcement — all bash commands must route through safe-run.sh
alwaysApply: true
---

# YAMTAM Security Gate — Cursor Hard Enforcement

**MANDATORY:** Every bash/shell command you generate MUST be prefixed with the safe-run proxy:

```
bash core/scripts/safe-run.sh --engine cursor <your command here>
```

## Examples

❌ FORBIDDEN:
```bash
rm -rf dist/
git push --force
```

✅ REQUIRED:
```bash
bash core/scripts/safe-run.sh --engine cursor rm -rf dist/
bash core/scripts/safe-run.sh --engine cursor git push --force
```

## Why

YAMTAM's L0–L5 gate stack screens every command for destructive patterns, LD_PRELOAD hijacks,
pipe-to-shell exploits, and elevated-risk operations before execution.
Cursor does not have a native hook layer — safe-run.sh is the enforcement proxy.

## Violations

Any command executed without the safe-run proxy is a TIER-2 security violation.
Log: /tmp/yamtam-audit.log
CURSOREOF
    echo -e "${GREEN}✓ Hard enforcement rule written${NC}: .cursor/rules/yamtam-hard-enforcement.mdc"
    echo ""
    echo -e "${CYAN}Cursor picks up these files automatically.${NC}"
    echo "Hard enforcement active — all bash calls must route through safe-run.sh --engine cursor"
    ;;

  copilot)
    INSTRUCTIONS=".github/copilot-instructions.md"
    if [[ -f "$INSTRUCTIONS" ]]; then
      echo -e "${GREEN}✓ $INSTRUCTIONS present${NC} ($(wc -l < "$INSTRUCTIONS") lines)"
    else
      echo -e "${RED}✗ $INSTRUCTIONS missing${NC}"
      exit 1
    fi
    echo ""
    echo -e "${CYAN}GitHub Copilot reads this file automatically in VS Code.${NC}"
    echo "Ensure: GitHub Copilot extension ≥ 1.100 for instructions support."
    ;;

  aider)
    ADAPTER="adapters/aider.md"
    if [[ ! -f "$ADAPTER" ]]; then
      echo -e "${RED}✗ $ADAPTER missing${NC}"
      exit 1
    fi
    echo -e "${GREEN}✓ Aider adapter ready${NC}"

    # ── Hard enforcement: write .aider.conf.yml with safe-run proxy ───────────
    cat > ".aider.conf.yml" << 'AIDEREOF'
# YAMTAM Hard Enforcement — Aider configuration
# Generated by: bash core/scripts/switch-engine.sh aider

# Route all bash commands through YAMTAM safe-run proxy
shell: bash core/scripts/safe-run.sh --engine aider

# Governance system prompt
system_prompt: adapters/aider.md

# Safety defaults
auto_commits: false
dirty_commits: false
auto_lint: false

# Prevent aider from running arbitrary install commands
read_only:
  - core/gates/
  - core/hooks/
  - core/memory/L1/
AIDEREOF
    echo -e "${GREEN}✓ Hard enforcement config written${NC}: .aider.conf.yml"
    echo ""
    echo -e "${CYAN}Run aider with YAMTAM governance:${NC}"
    echo ""
    echo "  aider --model claude-sonnet-4-6"
    echo ""
    echo "All bash commands routed through safe-run.sh --engine aider (Hard mode)"
    ;;

  gemini)
    ADAPTER="adapters/gemini-code.md"
    DEST="GEMINI.md"
    if [[ ! -f "$ADAPTER" ]]; then
      echo -e "${RED}✗ $ADAPTER missing${NC}"
      exit 1
    fi

    # Backup existing GEMINI.md before overwrite
    if [[ -f "$DEST" ]]; then
      BACKUP="${DEST}.bak.$(date +%Y%m%d_%H%M%S)"
      cp "$DEST" "$BACKUP"
      echo -e "${YELLOW}↩ Backup created:${NC} $BACKUP"
    fi

    # Generate GEMINI.md from adapter source (strip comment-only header lines)
    cp "$ADAPTER" "$DEST"
    echo -e "${GREEN}✓ Generated:${NC} $DEST ($(wc -l < "$DEST") lines)"

    # Log via secure-logger.sh if available
    LOGGER="core/scripts/secure-logger.sh"
    if [[ -x "$LOGGER" ]]; then
      bash "$LOGGER" engine_switch "gemini adapter activated — GEMINI.md written" 2>/dev/null || true
    fi

    echo ""
    echo -e "${CYAN}Enforcement tier summary:${NC}"
    echo "  L0  Audit    — every tool call logged (do not skip)"
    echo "  L1  Scope    — no secret/env access without declaration"
    echo "  L2  Commit   — warn on cross-scope commits"
    echo "  L3  Truth    — no unsupported completion claims"
    echo "  L4  Deploy   — requires YAMTAM_DEPLOY_APPROVED=1"
    echo "  L5  Destruct — hard block rm -rf / DROP TABLE / DELETE without WHERE"
    echo ""
    echo "GEMINI.md is read automatically by Gemini Code CLI on startup."
    echo "For shell-level blocking, additionally run:"
    echo "  bash core/scripts/safe-run.sh --engine gemini -- <command>"
    ;;

  qwen)
    ADAPTER="adapters/qwen.md"
    if [[ ! -f "$ADAPTER" ]]; then
      echo -e "${RED}✗ $ADAPTER missing${NC}"
      exit 1
    fi
    echo -e "${GREEN}✓ Qwen adapter ready${NC}: $ADAPTER"

    # Log via secure-logger.sh if available
    LOGGER="core/scripts/secure-logger.sh"
    if [[ -x "$LOGGER" ]]; then
      bash "$LOGGER" engine_switch "qwen adapter activated — advisory mode" 2>/dev/null || true
    fi

    echo ""
    echo -e "${YELLOW}⚠ ADVISORY_GAP_START${NC}"
    echo "  Qwen runs via OpenRouter — no native hook layer is available."
    echo "  Enforcement is prompt-advisory only; safe-run.sh is NOT auto-wired."
    echo "  For shell-level blocking, manually prefix commands:"
    echo "    bash core/scripts/safe-run.sh --engine qwen -- <command>"
    echo -e "${YELLOW}ADVISORY_GAP_END${NC}"
    echo ""
    echo -e "${CYAN}Enforcement tier summary (advisory):${NC}"
    echo "  L0  Audit    — advisory only (no native hook; log manually)"
    echo "  L1  Scope    — prompt-instructed (no runtime intercept)"
    echo "  L2  Commit   — prompt-instructed"
    echo "  L3  Truth    — prompt-instructed"
    echo "  L4  Deploy   — prompt-instructed (YAMTAM_DEPLOY_APPROVED=1 in prompt)"
    echo "  L5  Destruct — prompt-instructed (model refuses; not shell-blocked)"
    echo ""
    echo -e "${CYAN}Run Qwen via Aider + OpenRouter (use placeholders — do not paste real keys here):${NC}"
    echo ""
    echo "  # Qwen3 235B (flagship):"
    echo "  OPENROUTER_API_KEY=<your-key> aider \\"
    echo "    --model openrouter/qwen/qwen3-235b-a22b \\"
    echo "    --system-prompt adapters/qwen.md"
    echo ""
    echo "  # Qwen3 30B (fast):"
    echo "  OPENROUTER_API_KEY=<your-key> aider \\"
    echo "    --model openrouter/qwen/qwen3-30b-a3b \\"
    echo "    --system-prompt adapters/qwen.md"
    echo ""
    echo "  # Qwen2.5-Coder 32B:"
    echo "  OPENROUTER_API_KEY=<your-key> aider \\"
    echo "    --model openrouter/qwen/qwen2.5-coder-32b-instruct \\"
    echo "    --system-prompt adapters/qwen.md"
    echo ""
    echo "Set OPENROUTER_API_KEY in your shell environment — never hardcode it."
    ;;

  deepseek)
    ADAPTER="adapters/deepseek.md"
    if [[ ! -f "$ADAPTER" ]]; then
      echo -e "${RED}✗ $ADAPTER missing${NC}"
      exit 1
    fi
    echo -e "${GREEN}✓ DeepSeek adapter ready${NC}: $ADAPTER"

    # Log via secure-logger.sh if available
    LOGGER="core/scripts/secure-logger.sh"
    if [[ -x "$LOGGER" ]]; then
      bash "$LOGGER" engine_switch "deepseek adapter activated — advisory mode" 2>/dev/null || true
    fi

    echo ""
    echo -e "${YELLOW}⚠ ADVISORY_GAP_START${NC}"
    echo "  DeepSeek runs via Aider (direct API or OpenRouter) — no native hook layer."
    echo "  Enforcement is prompt-advisory only; safe-run.sh is NOT auto-wired."
    echo "  For shell-level blocking, manually prefix commands:"
    echo "    bash core/scripts/safe-run.sh --engine deepseek -- <command>"
    echo -e "${YELLOW}ADVISORY_GAP_END${NC}"
    echo ""
    echo -e "${CYAN}Enforcement tier summary (advisory):${NC}"
    echo "  L0  Audit    — advisory only (no native hook; log manually)"
    echo "  L1  Scope    — prompt-instructed (no runtime intercept)"
    echo "  L2  Commit   — prompt-instructed"
    echo "  L3  Truth    — prompt-instructed"
    echo "  L4  Deploy   — prompt-instructed (YAMTAM_DEPLOY_APPROVED=1 in prompt)"
    echo "  L5  Destruct — prompt-instructed (model refuses; not shell-blocked)"
    echo ""
    echo -e "${CYAN}Run DeepSeek via Aider (use placeholders — do not paste real keys here):${NC}"
    echo ""
    echo "  # DeepSeek V3 (direct API):"
    echo "  DEEPSEEK_API_KEY=<your-key> aider \\"
    echo "    --model deepseek/deepseek-chat \\"
    echo "    --system-prompt adapters/deepseek.md"
    echo ""
    echo "  # DeepSeek R1 — reasoning model (direct API):"
    echo "  DEEPSEEK_API_KEY=<your-key> aider \\"
    echo "    --model deepseek/deepseek-reasoner \\"
    echo "    --system-prompt adapters/deepseek.md"
    echo ""
    echo "  # DeepSeek V3 via OpenRouter:"
    echo "  OPENROUTER_API_KEY=<your-key> aider \\"
    echo "    --model openrouter/deepseek/deepseek-chat \\"
    echo "    --system-prompt adapters/deepseek.md"
    echo ""
    echo "Set DEEPSEEK_API_KEY or OPENROUTER_API_KEY in your shell — never hardcode it."
    ;;

  openrouter)
    ADAPTER="adapters/openrouter.md"
    if [[ ! -f "$ADAPTER" ]]; then
      echo -e "${RED}✗ $ADAPTER missing${NC}"
      exit 1
    fi
    echo -e "${GREEN}✓ OpenRouter adapter ready${NC}: $ADAPTER"

    # Log via secure-logger.sh if available
    LOGGER="core/scripts/secure-logger.sh"
    if [[ -x "$LOGGER" ]]; then
      bash "$LOGGER" engine_switch "openrouter adapter activated — advisory mode" 2>/dev/null || true
    fi

    echo ""
    echo -e "${YELLOW}⚠ ADVISORY_GAP_START${NC}"
    echo "  OpenRouter has no native YAMTAM hook layer."
    echo "  Tool calls in this session are NOT recorded in the YAMTAM Merkle audit chain."
    echo "  The engine_switch event above is the only audit entry for this session."
    echo "  Enforcement is prompt-advisory only; safe-run.sh is NOT auto-wired."
    echo "  For shell-level blocking, manually prefix commands:"
    echo "    bash core/scripts/safe-run.sh --engine openrouter -- <command>"
    echo -e "${YELLOW}ADVISORY_GAP_END${NC}"
    echo ""
    echo -e "${CYAN}Enforcement tier summary (advisory):${NC}"
    echo "  L0  Audit    — engine_switch logged; individual tool calls NOT in Merkle chain"
    echo "  L1  Scope    — prompt-instructed (no runtime intercept)"
    echo "  L2  Commit   — prompt-instructed"
    echo "  L3  Truth    — prompt-instructed"
    echo "  L4  Deploy   — prompt-instructed (YAMTAM_DEPLOY_APPROVED=1 in prompt)"
    echo "  L5  Destruct — prompt-instructed (model refuses; not shell-blocked)"
    echo ""
    echo -e "${CYAN}Run any OpenRouter model via Aider (use placeholders — do not paste real keys here):${NC}"
    echo ""
    echo "  OPENROUTER_API_KEY=<your-key> aider \\"
    echo "    --model openrouter/<provider>/<model-slug> \\"
    echo "    --openai-api-base https://openrouter.ai/api/v1 \\"
    echo "    --openai-api-key <your-key> \\"
    echo "    --no-auto-commits \\"
    echo "    --system-prompt adapters/openrouter.md"
    echo ""
    echo -e "${CYAN}Example model slugs:${NC}"
    echo "  openrouter/qwen/qwen3-235b-a22b"
    echo "  openrouter/deepseek/deepseek-chat"
    echo "  openrouter/mistralai/mistral-large"
    echo "  openrouter/meta-llama/llama-3.1-405b-instruct"
    echo "  openrouter/<provider>/<model-slug>   ← any OpenRouter-listed model"
    echo ""
    echo "Set OPENROUTER_API_KEY in your shell environment — never hardcode it."
    ;;

  status)
    echo "=== YAMTAM Engine Adapter Status ==="
    echo ""
    [[ -f ".cursorrules" ]] \
      && echo -e "  ${GREEN}✓${NC} Cursor    .cursorrules ($(wc -l < .cursorrules) lines)" \
      || echo -e "  ${YELLOW}✗${NC} Cursor    .cursorrules missing"
    [[ -d ".cursor/rules" ]] \
      && echo -e "  ${GREEN}✓${NC} Cursor    .cursor/rules/ ($(ls .cursor/rules/*.mdc 2>/dev/null | wc -l) .mdc files)" \
      || echo -e "  ${YELLOW}✗${NC} Cursor    .cursor/rules/ missing"
    [[ -f ".github/copilot-instructions.md" ]] \
      && echo -e "  ${GREEN}✓${NC} Copilot   .github/copilot-instructions.md" \
      || echo -e "  ${YELLOW}✗${NC} Copilot   .github/copilot-instructions.md missing"
    [[ -f "adapters/aider.md" ]] \
      && echo -e "  ${GREEN}✓${NC} Aider     adapters/aider.md" \
      || echo -e "  ${YELLOW}✗${NC} Aider     adapters/aider.md missing"
    [[ -f "GEMINI.md" ]] \
      && echo -e "  ${GREEN}✓${NC} Gemini    GEMINI.md ($(wc -l < GEMINI.md) lines)" \
      || echo -e "  ${YELLOW}✗${NC} Gemini    GEMINI.md missing"
    [[ -f "adapters/qwen.md" ]] \
      && echo -e "  ${GREEN}✓${NC} Qwen      adapters/qwen.md (advisory — no native hook)" \
      || echo -e "  ${YELLOW}✗${NC} Qwen      adapters/qwen.md missing"
    [[ -f "adapters/deepseek.md" ]] \
      && echo -e "  ${GREEN}✓${NC} DeepSeek   adapters/deepseek.md (advisory — no native hook)" \
      || echo -e "  ${YELLOW}✗${NC} DeepSeek   adapters/deepseek.md missing"
    [[ -f "adapters/openrouter.md" ]] \
      && echo -e "  ${GREEN}✓${NC} OpenRouter adapters/openrouter.md (advisory — Merkle gap)" \
      || echo -e "  ${YELLOW}✗${NC} OpenRouter adapters/openrouter.md missing"
    echo ""
    echo -e "  ${GREEN}✓${NC} Claude    native (hooks in core/hooks/)"
    ;;

  *)
    echo -e "${RED}Unknown engine: $ENGINE${NC}"
    usage
    ;;
esac
